### ISSUE TITLE
Invalid output conversion

### ISSUE THREAD

**Issue by azurit** [arskom/spyne#103]
rpclib is doing invalid output conversion of floats - if your function is supposed to return float and you will return string, value in XML is invalid (see that quotes):

```
<tns:testfResult>'1.1'</tns:testfResult>
```

server example:

```
import logging

from rpclib.application import Application
from rpclib.decorator import srpc
from rpclib.decorator import rpc
from rpclib.interface.wsdl import Wsdl11
from rpclib.protocol.soap import Soap11
from rpclib.service import ServiceBase
from rpclib.model.primitive import Integer
from rpclib.model.primitive import String
from rpclib.model.primitive import Float
from rpclib.model.complex import Array
from rpclib.model.complex import ComplexModel
from rpclib.server.wsgi import WsgiApplication

class tests(ServiceBase):

  @rpc(_returns=Float)
  def testf(ctx):
    return "1.1"

if __name__ == '__main__':
  from wsgiref.simple_server import make_server

  logging.basicConfig(level=logging.DEBUG)
  logging.getLogger('rpclib.protocol.xml').setLevel(logging.DEBUG)

  application = Application([tests], 'tests', interface=Wsdl11(), in_protocol=Soap11(validator="soft"), out_protocol=Soap11())

  host = "127.0.0.1"
  port = 8080

  server = make_server(host, port, WsgiApplication(application))

  print "listening to http://%s:%s" % (host, port)
  print "wsdl is at: http://%s:%s/?wsdl" % (host, port)

  server.serve_forever()
```

**Comment by liboz** [comment]
Is there a reason this isn't documented in the docs? It took me quite a while to figure out why I was getting returns like <result>Decimal('1.3254351')</result>

**Comment by plq** [comment]
this happened four years ago. I got rid of a lot of hacks, spyne codebase is much cleaner now :)

what types are you having trouble with?

**Comment by liboz** [comment]
I am using python's decimal type and serializing as soap11. When it comes out the result is something like Decimal('1.3254351') instead of just 1.3254351. This was quite confusing to me until I figured out I needed to customize the Decimal types to format with string instead of the default repr().

**Comment by plq** [comment]
which output type are you using? in this case the docs are right and `repr` should only be called work for Double and Float not Decimal.

**Comment by liboz** [comment]
Hmm you're correct that it only applies when having a Decimal type output as a Float/Double. I guess that is suboptimal, but it's unexpected that the code uses repr(value) instead of repr(float(value)) because it calls float(value) already anyways. This is line 467 in spyne.protocol._base.

**Comment by plq** [comment]
The transformation between `float` and `Decimal` is always problematic.

>>> Decimal(float(0.1))
Decimal('0.1000000000000000055511151231257827021181583404541015625')

As you see, it's best to do the conversion in user code. There are no sane defaults to satisfy everyone.

**Comment by liboz** [comment]
It makes sense why you do this. I would be nice to have it documented that attempting to output a Decimal type as a Float/Double will result in strange things like `Decimal('1.3254351')` returning. The commit you just made is also helpful.

**Comment by plq** [comment]
anything else I can do for you? :)

**Comment by liboz** [comment]
Nope, thanks for your assistance.
