### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by plq** [arskom/spyne#113]
let's see how this goes...

**Comment by alexandre-figura** [comment]
If I use the ``HttpClient`` in Python 3, when calling a method of my service, I have a ``TypeError``. Here is the end of the traceback:


    Traceback (most recent call last):
      ......
      File "/home/user/dev/spyne/spyne/client/http.py", line 43, in __call__
        out_string = ''.join(self.ctx.out_string) # FIXME: just send the iterable to the http stream.

    TypeError: sequence item 0: expected str instance, bytes found

The value of ``self.ctx.out_string`` is:

    [b'<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<soap11env:Envelope xmlns:soap11env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="XXX"><soap11env:Body>......</soap11env:Body></soap11env:Envelope>']

As a hack, I tried to force the use of a binary type in ``spyne/http/client.py:43``:

    out_string = b''.join(self.ctx.out_string)

And that works! But I don't think this is the good way to fix this issue.

**Comment by plq** [comment]
Thanks for sharing this!

Many random instances of that popping up from everywhere because nobody knows right know which function returns `bytes` and which returns `str`. That's going to be the priority of the next release, hopefully.

**Comment by plq** [comment]
ok, the grunt work for the remaining parts of spyne is mostly complete. now comes the hard part -- real world testing.
