### ISSUE TITLE
Can't put 2 versions of service in the same application

### ISSUE THREAD

**Issue by DXist** [arskom/spyne#344]
I want my spyne application to handle several versions of my service. I have two copies of the same service with spyne models bound to different namespaces.

However methods of both services are placed into the same namespace and I get following error:
```
classes <class 'spyne.model._base.method_name'> and <class 'spyne.model._base.method_name'> have conflicting names

```

**Comment by plq** [comment]
If #459 doesn't fix this, please reopen with (hopefully new) findings.
