### ISSUE TITLE
follow on to #385 - parsing xsi_type when namespace prefix not present

### ISSUE THREAD

**Issue by jrocnuck** [arskom/spyne#411]
We need to handle the case when the namespace prefix is not present when parsing xsi types.

in this file:
https://github.com/arskom/spyne/blob/7243e9632af2348ce97cc3be2ffdeaeec9094779/spyne/protocol/xml.py#L389
the lines:

     prefix, objtype = xsi_type.split(':', 1)
     classkey = "{%s}%s" % (element.nsmap[prefix], objtype)

need to change to something like this:

     if ":" in xsi_type:
          prefix, objtype = xsi_type.split(':', 1)
          classkey = "{%s}%s" % (element.nsmap[prefix], objtype)
     else:
         classkey = xsi_type

**Comment by plq** [comment]
the classkey needs to contain the namespace as well, so are you sure `classkey = xsi_type` is correct?

**Comment by jrocnuck** [comment]
From my experience so far ctx.app.interfaces.classes has keys for both namespace prefixed xsi type and non namespace prefixed xsi type.  I am thinking the proper way to do this when there is no namespace prefix, we should grab the default namespace (xmlns) from the xml and put it in as the namespace.  I am not sure what should be done if a default namespace is not provided.  My initial thought would be to attempt a lookup the object in the classes dictionary and fail to None for the returned object as it is coded currently.

**Comment by plq** [comment]
When a non-existing namespace is referred, that's a validation error, which is what I did above.

I consider this issue now solved. Thanks for your help.

**Comment by jrocnuck** [comment]
I'm still not sure if the final solution is 100% correct.  I think I used the wrong wording.  I didn't mean a non existing namespace, what I meant is when the prefix is not provided inside the xsi:type="" attribute.
For example if we receive
 
      <ns0:mytag xsi:type="MyTagObj">.....</>

I do not think that breaks validation (per section 2 of this note on QName: http://www.w3.org/TR/xmlschema-1/#src-qname)

In the code that you committed (this line: https://github.com/plq/spyne/commit/b4b461896dd66cebfb1c858afd2a0b01a861ebbd#diff-2022aba7fde8c378953bf1f224fbaa41R394)

I would expect that if prefix = None the line
     
     ns = element.nsmap.get(prefix)

would always return None.

If the prefix is actually None, that does not mean that the type/object specified in xsi:type does not exist, it means that the client has not been specific about which namespace from which to extract the object in the xsi:type attribute.

here's an example:

```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soapenv:Body>
      <ns1:CorticonResponse decisionServiceName="TerritoryAssignment" xmlns:ns1="urn:Corticon">
         <ns1:WorkDocuments messageType="HIER">
            <ns1:Account id="0013000000VwnYUAAZ">
                <ns1:sfdcAccountId>0013000000VwnYUAAZ</ns1:sfdcAccountId>
               <ns1:stateProvince>Tokyo</ns1:stateProvince>
               <ns1:accountTeamMember id="AccountTeamMember_id_1" xsi:type="AccountTeamMember">

```
in that case the namespace isn't on the xsi:type attribute of accountTeamMember, but it is on the accountTeamMember xml tag/name

**Comment by plq** [comment]
None is the prefix for the default namespace:

'''
>>> from lxml import etree
>>> etree.fromstring('<a xmlns="ns"/>').nsmap
{None: 'ns'}
'''

> If the prefix is actually None, that does not mean that the type/object specified in xsi:type does not exist, it means that the client has not been specific about which namespace from which to extract the object in the xsi:type attribute.

No, when the ns prefix is missing, that means the object is in default namespace, i.e. whatever's the most recent `xmlns="some_ns"`. If the document at hand doesn't a default namespace, then the value in xsi:type is invalid, hence the validation error. that's what I understand from the qname note section of the standard that you linked.

> I discovered that classes were in the dictionary by the key and by the prefix:key, so that seemed to be useful for this particular case when xsi:type is missing prefix.

That's strange. I'll investigate that.

**Comment by jrocnuck** [comment]
Ok, I didn't realize nsmap stored a value for None key, so I've learned something new on that one and also then that makes your solution 100% valid as far as I can tell.  Thanks for fixing quickly and for clearing me up on the etree piece.
