### ISSUE TITLE
BODY_STYLE_BARE automagically changed into BODY_STYLE_EMPTY

### ISSUE THREAD

**Issue by xavfernandez** [arskom/spyne#412]
I don't understand all the inner working of BODY_STYLE but ended having to hack around it:
The lines concerned are:
https://github.com/arskom/spyne/blob/master/spyne/decorator.py#L333-L339
which change a 'bare' body style into an 'empty' one.

I would be fine with it but this has implications on the name of the method:
https://github.com/arskom/spyne/blob/master/spyne/_base.py#L425-L429

So I ended up adding an optional dummy field on my in_message object so that spyne does not consider it as empty and does not change my method name. This is an unfortunate hack.

Maybe it should be:

    if body_style is BODY_STYLE_BARE or body_style is BODY_STYLE_EMPTY:
        self.name = in_message.Attributes.sub_name

or maybe Spyne should not try to guess that body_style == 'bare' can mean 'empty' and let the user specify it ?

**Comment by plq** [comment]
if method name changes because body_style changes, it's a bug. can you provide a test case?

**Comment by xavfernandez** [comment]
Well it comes directly from:
https://github.com/arskom/spyne/blob/master/spyne/_base.py#L425-L429
if 'bare', we have in_message.Attributes.sub_name
if 'empty', we have self.in_message.get_type_name()

**Comment by plq** [comment]
hm. I guess I see where i'm coming from :) let me think

**Comment by plq** [comment]
I think that line should have been 

```
 if body_style in (BODY_STYLE_BARE, BODY_STYLE_EMPTY):
```

no?

**Comment by xavfernandez** [comment]
Yes that is also what I thought:

    if body_style is BODY_STYLE_BARE or body_style is BODY_STYLE_EMPTY:

But I am not certain :)
I'm trying to write a test

**Comment by plq** [comment]
I agree that's the way to go.
