### ISSUE TITLE
segfault from Spyne when too many arguments

### ISSUE THREAD

**Issue by juliengreard** [arskom/spyne#421]
Hello,

I'm really not sure if it's a Spyne issue - forgive me if it's not - but I have segfaults when I call a spyne service which has more than 10 arguments (14 in my case).

My case - it's a little long, but I tried to tell the whole context:

I have a server which runs Spyne. At first start of my service, I inspect several directories to dynamically build some Spyne Services, I also have some services which are not "directory dependant" ie which are written in pure Spyne code (@rpc decorator, etc). Finally I generate a wsdl file: so far, it's OK.

Then I try to call my services with a Soap Client (SoapUI for instance) which I initiate with the WSDL. 
- If I call a "native" service with 14 arguments, everything is OK no matter how many times I call it
- When I call the same service but when it's "dynamically built", then in 20% of the cases I timeout. When I look at the server status after that, it's stuck, due apparently to a segfault.

If I call my service dynamically built directly (from inside Python code), I get no error, so in my opinion, the bug is linked to Spyne, maybe Spyne has difficulties to manage too many arguments in one single request?

I've tryed to get more information about the segfault, but I have no clue so far. I've opened a question on SO on how to debug stuck process in python, but didn't get answers yet.
Here my SO link : http://stackoverflow.com/questions/28108851/catching-segfault-with-debugger-in-python

I'm really not sure the problem in on Spyne side, but I would be glade to have the opinion on Spyne team about it.

Thanks

**Comment by plq** [comment]
A segfault? Wow, that's new. I very much doubt it's Spyne related as anything that segfaults is either a CPython or lxml bug. Spyne might be triggering it but I'm almost sure that this will have to be escalated.

Please provide a script that reproduces this bug.

**Comment by juliengreard** [comment]
Thanks for the answer. I can't provide a script as everything is interlinked in more than 100 py files... but I can provide a backtrace (cf below), do you want it in a more readable way ?

==================== BACKTRACE ======================

(gdb) bt
#0  0x0000000000522fa3 in PyEval_EvalCodeEx (co=0x1db1bf0, globals=
    {'Loggers': <classobj at remote 0x1202cd8>, 'transform_function': <function at remote 0x1289840>, 'get_method_prototype': <function at remote 0x1289798>, 'Container': <Container(signature_map={}) at remote 0x1285678>, '__builtins__': {'bytearray': <type at remote 0x85ffe0>, 'IndexError': <type at remote 0x866620>, 'all': <built-in function all>, 'help': <_Helper at remote 0xb70ae0>, 'vars': <built-in function vars>, 'SyntaxError': <type at remote 0x865fa0>, 'unicode': <type at remote 0x87d300>, 'UnicodeDecodeError': <type at remote 0x866f40>, 'memoryview': <type at remote 0x870ec0>, 'isinstance': <built-in function isinstance>, 'copyright': <_Printer(_Printer__data='Copyright (c) 2001-2012 Python Software Foundation.\nAll Rights Reserved.\n\nCopyright (c) 2000 BeOpen.com.\nAll Rights Reserved.\n\nCopyright (c) 1995-2001 Corporation for National Research Initiatives.\nAll Rights Reserved.\n\nCopyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.\nAll Rights Reserved.', _Printer__lines=None, _Printe...(truncated), locals=0x0, args=0x1d44340, 
    argcount=16, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at ../Python/ceval.c:3071
#1  0x0000000000464841 in function_call (func=<function at remote 0x1db2f78>, arg=
    (<WsgiMethodContext(function=<function at remote 0x1db2f78>, out_body_doc=None, protocol=<ProtocolContext(itself=<WsgiApplication(_wsdl=None, max_content_length=2097152, doc=<AllYourInterfaceDocuments(wsdl11=<Wsdl11(service_elt=None, service_elt_dict={}, _with_plink=False, root_elt=None, validation_schema=None, namespaces=<odict(_odict__list=['tns']) at remote 0x2075300>, port_type_dict={}, interface=<Interface(_Interface__ns_counter=2, deps={<ComplexModelMeta(_type_info={'string': <type at remote 0x16cd0d0>}, __module__='spyne.model.complex', __orig__=<ComplexModelMeta(_type_info=<TypeInfo(attributes={}, _odict__list=[]) at remote 0x1741fb0>, __module__='spyne.model.complex', _type_info_alt=<TypeInfo(attributes={}, _odict__list=[]) at remote 0x1464d30>, Push=<type at remote 0x1741bc0>, Attributes=<AttributesMeta(__module__='spyne.model.complex', sqla_table_args=None, logged=False, sqla_metadata=None, sqla_table=None, table_name=None, _nullable=None, _variants=<WeakKeyDictionary(_remove=<function at remote 0x...(truncated), kw=0x0)
    at ../Objects/funcobject.c:526
#2  0x000000000042882b in PyObject_Call (func=<function at remote 0x1db2f78>, arg=
    (<WsgiMethodContext(function=<function at remote 0x1db2f78>, out_body_doc=None, protocol=<ProtocolContext(itself=<WsgiApplication(_wsdl=None, max_content_length=2097152, doc=<AllYourInterfaceDocuments(wsdl11=<Wsdl11(service_elt=None, service_elt_dict={}, _with_plink=False, root_elt=None, validation_schema=None, namespaces=<odict(_odict__list=['tns']) at remote 0x2075300>, port_type_dict={}, interface=<Interface(_Interface__ns_counter=2, deps={<ComplexModelMeta(_type_info={'string': <type at remote 0x16cd0d0>}, __module__='spyne.model.complex', __orig__=<ComplexModelMeta(_type_info=<TypeInfo(attributes={}, _odict__list=[]) at remote 0x1741fb0>, __module__='spyne.model.complex', _type_info_alt=<TypeInfo(attributes={}, _odict__list=[]) at remote 0x1464d30>, Push=<type at remote 0x1741bc0>, Attributes=<AttributesMeta(__module__='spyne.model.complex', sqla_table_args=None, logged=False, sqla_metadata=None, sqla_table=None, table_name=None, _nullable=None, _variants=<WeakKeyDictionary(_remove=<function at remote 0x...(truncated), kw=0x0)
    at ../Objects/abstract.c:2529
#3  0x0000000000527901 in ext_do_call (func=<function at remote 0x1db2f78>, pp_stack=0x7fffd0ff4f10, flags=1, na=1, nk=0)
    at ../Python/ceval.c:4334
#4  0x00000000005215cd in PyEval_EvalFrameEx (f=
    Frame 0x7fffb8016050, for file /usr/local/lib/python2.7/dist-packages/spyne-2.11.0-py2.7.egg/spyne/service.py, line 210, in call_wrapper (cls=<ServiceBaseMeta(__module__='agent.soap.services.ServicesAvailable', mandatory_input=<staticmethod at remote 0x1f04470>, returns_string=<staticmethod at remote 0x1f046e0>, many_args=<staticmethod at remote 0x1f048e8>, _ServiceBaseMeta__has_aux_methods=False, returns_list=<staticmethod at remote 0x1f045a8>, optional_input=<staticmethod at remote 0x1f044d8>, many_args_9=<staticmethod at remote 0x1f04748>, __tns__='spyne.examples.hello', event_manager=<EventManager(parent=<...>, handlers={}) at remote 0x1f07610>, public_methods={'mandatory_input': <MethodDescriptor(in_message_name_override=True, service_class=<...>, mtom=False, out_message=<ComplexModelMeta(__module__='spyne.model.complex', __type_name__='mandatory_inputResponse', _type_info=<TypeInfo(attributes={}, _odict__list=['mandatory_inputResult']) at remote 0x1f3be90>, _type_info_alt=<TypeInfo(attributes={}, _odict...(truncated), throwflag=0)
    at ../Python/ceval.c:2705
#5  0x0000000000526921 in fast_function (func=<function at remote 0x17826f0>, pp_stack=0x7fffd0ff5270, n=2, na=2, nk=0)
    at ../Python/ceval.c:4107
#6  0x0000000000526631 in call_function (pp_stack=0x7fffd0ff5270, oparg=1) at ../Python/ceval.c:4042
#7  0x0000000000521326 in PyEval_EvalFrameEx (f=
    Frame 0x7fffb8015e10, for file /usr/local/lib/python2.7/dist-packages/spyne-2.11.0-py2.7.egg/spyne/application.py, line 199, in call_wrapper (self=<Application(name='Application', tns='spyne.examples.hello', in_protocol=<Soap11(cleanup_namespaces=True, ignore_wrappers=False, _to_string_iterable_handlers=<cdict at remote 0x1ed65e0>, deserialization_handlers=<cdict at remote 0x1f6ebb0>, log_messages=False, _to_string_handlers=<cdict at remote 0x1f6a400>, pretty_print=False, validate_document=<instancemethod at remote 0x1ad4c60>, ignore_uncap=False, _datetime_dsmap={'usec': <instancemethod at remote 0x1f12ce0>, 'msec': <instancemethod at remote 0x1f12be0>, 'msec_float': <instancemethod at remote 0x1f12c60>, 'sec': <instancemethod at remote 0x1f12ae0>, 'sec_float': <instancemethod at remote 0x1f12b6---Type <return> to continue, or q <return> to quit---inf^CQuit

==================== PY-BACKTRACE ======================

(gdb) py-bt
#4 Frame 0x7fffb8016050, for file /usr/local/lib/python2.7/dist-packages/spyne-2.11.0-py2.7.egg/spyne/service.py, line 210, in call_wrapper (cls=<ServiceBaseMeta(__module__='agent.soap.services.ServicesAvailable', mandatory_input=<staticmethod at remote 0x1f04470>, returns_string=<staticmethod at remote 0x1f046e0>, many_args=<staticmethod at remote 0x1f048e8>, _ServiceBaseMeta__has_aux_methods=False, returns_list=<staticmethod at remote 0x1f045a8>, optional_input=<staticmethod at remote 0x1f044d8>, many_args_9=<staticmethod at remote 0x1f04748>, __tns__='spyne.examples.hello', event_manager=<EventManager(parent=<...>, handlers={}) at remote 0x1f07610>, public_methods={'mandatory_input': <MethodDescriptor(in_message_name_override=True, service_class=<...>, mtom=False, out_message=<ComplexModelMeta(__module__='spyne.model.complex', __type_name__='mandatory_inputResponse', _type_info=<TypeInfo(attributes={}, _odict__list=['mandatory_inputResult']) at remote 0x1f3be90>, _type_info_alt=<TypeInfo(attributes={}, _odict...(truncated)
    return ctx.function(ctx, *ctx.in_object)
#7 Frame 0x7fffb8015e10, for file /usr/local/lib/python2.7/dist-packages/spyne-2.11.0-py2.7.egg/spyne/application.py, line 199, in call_wrapper (self=<Application(name='Application', tns='spyne.examples.hello', in_protocol=<Soap11(cleanup_namespaces=True, ignore_wrappers=False, _to_string_iterable_handlers=<cdict at remote 0x1ed65e0>, deserialization_handlers=<cdict at remote 0x1f6ebb0>, log_messages=False, _to_string_handlers=<cdict at remote 0x1f6a400>, pretty_print=False, validate_document=<instancemethod at remote 0x1ad4c60>, ignore_uncap=False, _datetime_dsmap={'usec': <instancemethod at remote 0x1f12ce0>, 'msec': <instancemethod at remote 0x1f12be0>, 'msec_float': <instancemethod at remote 0x1f12c60>, 'sec': <instancemethod at remote 0x1f12ae0>, 'sec_float': <instancemethod at remote 0x1f12b60>, None: <instancemethod at remote 0x1f12a60>}, encoding='UTF-8', serialization_handlers=<cdict at remote 0x1f6d4e0>, _from_string_handlers=<cdict at remote 0x1f6d380>, validator=<type at remote 0x19b1430>, validation...(truncated)
    retval = ctx.descriptor.service_class.call_wrapper(ctx)
#10 Frame 0x7fffb802a610, for file /usr/local/lib/python2.7/dist-packages/spyne-2.11.0-py2.7.egg/spyne/application.py, line 144, in process_request (self=<Application(name='Application', tns='spyne.examples.hello', in_protocol=<Soap11(cleanup_namespaces=True, ignore_wrappers=False, _to_string_iterable_handlers=<cdict at remote 0x1ed65e0>, deserialization_handlers=<cdict at remote 0x1f6ebb0>, log_messages=False, _to_string_handlers=<cdict at remote 0x1f6a400>, pretty_print=False, validate_document=<instancemethod at remote 0x1ad4c60>, ignore_uncap=False, _datetime_dsmap={'usec': <instancemethod at remote 0x1f12ce0>, 'msec': <instancemethod at remote 0x1f12be0>, 'msec_float': <instancemethod at remote 0x1f12c60>, 'sec': <instancemethod at remote 0x1f12ae0>, 'sec_float': <instancemethod at remote 0x1f12b60>, None: <instancemethod at remote 0x1f12a60>}, encoding='UTF-8', serialization_handlers=<cdict at remote 0x1f6d4e0>, _from_string_handlers=<cdict at remote 0x1f6d380>, validator=<type at remote 0x19b1430>, validat...(truncated)
    ctx.out_object = self.call_wrapper(ctx)
#13 Frame 0x7fffb8029830, for file /usr/local/lib/python2.7/dist-packages/spyne-2.11.0-py2.7.egg/spyne/server/_base.py, line 103, in get_out_object (self=<WsgiApplication(_wsdl=None, max_content_length=2097152, doc=<AllYourInterfaceDocuments(wsdl11=<Wsdl11(service_elt=None, service_elt_dict={}, _with_plink=False, root_elt=None, validation_schema=None, namespaces=<odict(_odict__list=['tns']) at remote 0x2075300>, port_type_dict={}, interface=<Interface(_Interface__ns_counter=2, deps={<ComplexModelMeta(_type_info={'string': <type at remote 0x16cd0d0>}, __module__='spyne.model.complex', __orig__=<ComplexModelMeta(_type_info=<TypeInfo(attributes={}, _odict__list=[]) at remote 0x1741fb0>, __module__='spyne.model.complex', _type_info_alt=<TypeInfo(attributes={}, _odict__list=[]) at remote 0x1464d30>, Push=<type at remote 0x1741bc0>, Attributes=<AttributesMeta(__module__='spyne.model.complex', sqla_table_args=None, logged=False, sqla_metadata=None, sqla_table=None, table_name=None, _nullable=None, _variants=<WeakKeyDict...(truncated)
    self.app.process_request(ctx)
#16 Frame 0x7fffb40b7420, for file /usr/local/lib/python2.7/dist-packages/spyne-2.11.0-py2.7.egg/spyne/server/wsgi.py, line 348, in handle_rpc (self=<WsgiApplication(_wsdl=None, max_content_length=2097152, doc=<AllYourInterfaceDocuments(wsdl11=<Wsdl11(service_elt=None, service_elt_dict={}, _with_plink=False, root_elt=None, validation_schema=None, namespaces=<odict(_odict__list=['tns']) at remote 0x2075300>, port_type_dict={}, interface=<Interface(_Interface__ns_counter=2, deps={<ComplexModelMeta(_type_info={'string': <type at remote 0x16cd0d0>}, __module__='spyne.model.complex', __orig__=<ComplexModelMeta(_type_info=<TypeInfo(attributes={}, _odict__list=[]) at remote 0x1741fb0>, __module__='spyne.model.complex', _type_info_alt=<TypeInfo(attributes={}, _odict__list=[]) at remote 0x1464d30>, Push=<type at remote 0x1741bc0>, Attributes=<AttributesMeta(__module__='spyne.model.complex', sqla_table_args=None, logged=False, sqla_metadata=None, sqla_table=None, table_name=None, _nullable=None, _variants=<WeakKeyDictionar...(truncated)
    self.get_out_object(p_ctx)
#19 Frame 0x7fffd80029d0, for file /usr/local/lib/python2.7/dist-packages/spyne-2.11.0-py2.7.egg/spyne/server/wsgi.py, line 232, in __call__ (self=<WsgiApplication(_wsdl=None, max_content_length=2097152, doc=<AllYourInterfaceDocuments(wsdl11=<Wsdl11(service_elt=None, service_elt_dict={}, _with_plink=False, root_elt=None, validation_schema=None, namespaces=<odict(_odict__list=['tns']) at remote 0x2075300>, port_type_dict={}, interface=<Interface(_Interface__ns_counter=2, deps={<ComplexModelMeta(_type_info={'string': <type at remote 0x16cd0d0>}, __module__='spyne.model.complex', __orig__=<ComplexModelMeta(_type_info=<TypeInfo(attributes={}, _odict__list=[]) at remote 0x1741fb0>, __module__='spyne.model.complex', _type_info_alt=<TypeInfo(attributes={}, _odict__list=[]) at remote 0x1464d30>, Push=<type at remote 0x1741bc0>, Attributes=<AttributesMeta(__module__='spyne.model.complex', sqla_table_args=None, logged=False, sqla_metadata=No---Type <return> to continue, or q <return> to quit---
ne, sqla_table=None, table_name=None, _nullable=None, _variants=<WeakKeyDictionary(...(truncated)
    return self.handle_rpc(req_env, start_response)
#29 Frame 0x7fffc40b8170, for file /usr/lib/python2.7/wsgiref/handlers.py, line 85, in run (self=<ServerHandler(wsgi_multithread=True, stdout=<_fileobject at remote 0x2111110>, stdin=<_fileobject at remote 0x1e55e20>, wsgi_multiprocess=False, base_env={'CONTENT_TYPE': 'text/xml;charset=UTF-8', 'SCRIPT_NAME': '', 'REQUEST_METHOD': 'POST', 'HTTP_HOST': '192.168.10.50:7889', 'PATH_INFO': '/', 'SERVER_PROTOCOL': 'HTTP/1.1', 'QUERY_STRING': '', 'CONTENT_LENGTH': '1247', 'HTTP_SOAPACTION': '"many_args"', 'HTTP_CONNECTION': 'Keep-Alive', 'HTTP_USER_AGENT': 'Apache-HttpClient/4.1.1 (java 1.5)', 'SERVER_NAME': 'florent.intranet.evitech', 'GATEWAY_INTERFACE': 'CGI/1.1', 'REMOTE_ADDR': '192.168.10.50', 'SERVER_PORT': '7889', 'REMOTE_HOST': 'florent.intranet.evitech', 'HTTP_ACCEPT_ENCODING': 'gzip,deflate'}, environ={'HISTTIMEFORMAT': '%d/%m/%y %T ', 'LESS': '-R', 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.3', 'SCRIPT_NAME': '', 'REQUEST_METHOD': 'POST', 'SERVER_PROTOCOL': 'HTTP/1.1', 'CONTENT_LENGTH': '1247', 'SHELL': '/...(truncated)
    self.result = application(self.environ, self.start_response)
#32 Frame 0x7fffcc0021c0, for file /usr/lib/python2.7/wsgiref/simple_server.py, line 124, in handle (self=<LogRequestHandler(requestline='POST / HTTP/1.1', wfile=<_fileobject at remote 0x2111110>, request=<_socketobject at remote 0x21199c0>, raw_requestline='POST / HTTP/1.1\r\n', server=<ThreadedWSGIServer(RequestHandlerClass=<classobj at remote 0x1a63650>, base_environ={'CONTENT_LENGTH': '', 'SERVER_NAME': 'florent.intranet.evitech', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SCRIPT_NAME': '', 'SERVER_PORT': '7889', 'REMOTE_HOST': ''}, allow_reuse_address=True, _BaseServer__shutdown_request=False, server_name='florent.intranet.evitech', server_address=('0.0.0.0', 7889), application=<WsgiApplication(_wsdl=None, max_content_length=2097152, doc=<AllYourInterfaceDocuments(wsdl11=<Wsdl11(service_elt=None, service_elt_dict={}, _with_plink=False, root_elt=None, validation_schema=None, namespaces=<odict(_odict__list=['tns']) at remote 0x2075300>, port_type_dict={}, interface=<Interface(_Interface__ns_counter=2, deps={<ComplexMode...(truncated)
    handler.run(self.server.get_app())
#35 Frame 0x7fffbc0b70c0, for file /usr/lib/python2.7/SocketServer.py, line 638, in __init__ (self=<LogRequestHandler(requestline='POST / HTTP/1.1', wfile=<_fileobject at remote 0x2111110>, request=<_socketobject at remote 0x21199c0>, raw_requestline='POST / HTTP/1.1\r\n', server=<ThreadedWSGIServer(RequestHandlerClass=<classobj at remote 0x1a63650>, base_environ={'CONTENT_LENGTH': '', 'SERVER_NAME': 'florent.intranet.evitech', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SCRIPT_NAME': '', 'SERVER_PORT': '7889', 'REMOTE_HOST': ''}, allow_reuse_address=True, _BaseServer__shutdown_request=False, server_name='florent.intranet.evitech', server_address=('0.0.0.0', 7889), application=<WsgiApplication(_wsdl=None, max_content_length=2097152, doc=<AllYourInterfaceDocuments(wsdl11=<Wsdl11(service_elt=None, service_elt_dict={}, _with_plink=False, root_elt=None, validation_schema=None, namespaces=<odict(_odict__list=['tns']) at remote 0x2075300>, port_type_dict={}, interface=<Interface(_Interface__ns_counter=2, deps={<ComplexModelMeta(_...(truncated)
    self.handle()
#46 Frame 0x7fffc8002d90, for file /usr/lib/python2.7/SocketServer.py, line 323, in finish_request (self=<ThreadedWSGIServer(RequestHandlerClass=<classobj at remote 0x1a63650>, base_environ={'CONTENT_LENGTH': '', 'SERVER_NAME': 'florent.intranet.evitech', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SCRIPT_NAME': '', 'SERVER_PORT': '7889', 'REMOTE_HOST': ''}, allow_reuse_address=True, _BaseServer__shutdown_request=False, server_name='florent.intranet.evitech', server_address=('0.0.0.0', 7889), application=<WsgiApplication(_wsdl=None, max_content_length=2097152, doc=<AllYourInterfaceDocuments(wsdl11=<Wsdl11(service_elt=None, service_elt_dict={}, _with_plink=False, root_elt=None, validation_schema=None, namespaces=<odict(_odict__list=['tns']) at remote 0x2075300>, port_type_dict={}, interface=<Interface(_Interface__ns_counter=2, deps={<ComplexModelMeta(_type_info={'string': <type at remote 0x16cd0d0>}, __module__='spyne.model.complex', __orig__=<ComplexModelMeta(_type_info=<TypeInfo(attributes={}, _odict__list=[]) at remote 0x...(truncated)
    self.RequestHandlerClass(request, client_address, self)
#49 Frame 0x1d22a00, for file /usr/lib/python2.7/SocketServer.py, line 582, in process_request_thread (self=<ThreadedWSGIServer(RequestHandlerClass=<classobj at remote 0x1a63650>, base_environ={'CONTENT_LENGTH': '', 'SERVER_NAME': 'florent.intranet.evitech', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SCRIPT_NAME': '', 'SERVER_PORT': '7889', 'REMOTE_HOST': ''}, allow_reuse_address=True, _BaseServer__shutdown_request=False, server_name='florent.intranet.evitech', server_address=('0.0.0.0', 7889), application=<WsgiApplication(_wsdl=None, max_content_length=2097152, doc=<AllYourInterfaceDocuments(wsdl11=<Wsdl11(service_elt=None, service_elt_dict={}, _with_plink=False, root_elt=None, validation_schema=None, namespaces=<odict(_odict__list=['tns']) at remote 0x2075300>, port_type_dict={}, interface=<Interface(_Interface__ns_counter=2, deps={<ComplexModelMeta(_type_info={'string': <type at remote 0x16cd0d0>}, __module__='spyne.model.complex', __orig__=<ComplexModelMeta(_type_info=<TypeInfo(attributes={}, _odict__list=[]) at remote...(truncated)
    self.finish_request(request, client_address)
#54 Frame 0x207e470, for file /usr/lib/python2.7/threading.py, line 504, in run (self=<Thread(_Thread__ident=140736699799296, _Thread__block=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x21290e0>, acquire=<built-in method acquire of thread.lock object at remote 0x21290e0>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x21290e0>) at remote 0x2121ca0>, _Thread__name='Thread-14', _Thread__daemonic=True, _Thread__started=<_Event(_Verbose__verbose=False, _Event__flag=True, _Event__cond=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x2129090>, acquire=<built-in metho---Type <return> to continue, or q <return> to quit---
d acquire of thread.lock object at remote 0x2129090>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x2129090>) at remote 0x21213e0>) at remote 0x2121840>, _Thread__stderr=<file at remote 0x7ffff7fbb340>, _Thread__target=<instancemethod at remote 0x211cce0>, _Thread__kwargs={}, _Verbose__verbose=False, _Threa...(truncated)
    self.__target(*self.__args, **self.__kwargs)
#57 Frame 0x2064810, for file /usr/lib/python2.7/threading.py, line 551, in __bootstrap_inner (self=<Thread(_Thread__ident=140736699799296, _Thread__block=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x21290e0>, acquire=<built-in method acquire of thread.lock object at remote 0x21290e0>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x21290e0>) at remote 0x2121ca0>, _Thread__name='Thread-14', _Thread__daemonic=True, _Thread__started=<_Event(_Verbose__verbose=False, _Event__flag=True, _Event__cond=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x2129090>, acquire=<built-in method acquire of thread.lock object at remote 0x2129090>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x2129090>) at remote 0x21213e0>) at remote 0x2121840>, _Thread__stderr=<file at remote 0x7ffff7fbb340>, _Thread__target=<instancemethod at remote 0x211cce0>, _Thread__kwargs={}, _Verbose__verbose...(truncated)
    self.run()
#60 Frame 0x7fffbc002d30, for file /usr/lib/python2.7/threading.py, line 524, in __bootstrap (self=<Thread(_Thread__ident=140736699799296, _Thread__block=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x21290e0>, acquire=<built-in method acquire of thread.lock object at remote 0x21290e0>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x21290e0>) at remote 0x2121ca0>, _Thread__name='Thread-14', _Thread__daemonic=True, _Thread__started=<_Event(_Verbose__verbose=False, _Event__flag=True, _Event__cond=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x2129090>, acquire=<built-in method acquire of thread.lock object at remote 0x2129090>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x2129090>) at remote 0x21213e0>) at remote 0x2121840>, _Thread__stderr=<file at remote 0x7ffff7fbb340>, _Thread__target=<instancemethod at remote 0x211cce0>, _Thread__kwargs={}, _Verbose__verbose=...(truncated)

==================== PY-LIST ======================
(gdb) py-list 
 205    
 206            if ctx.function is not None:
 207                if ctx.descriptor.no_ctx:
 208                    return ctx.function(*ctx.in_object)
 209                else:
>210                    return ctx.function(ctx, *ctx.in_object)
(gdb) py-print ctx
local 'ctx' = <WsgiMethodContext(function=<function at remote 0x1db2f78>, out_body_doc=None, protocol=<ProtocolContext(itself=<WsgiApplication(_wsdl=None, max_content_length=2097152, doc=<AllYourInterfaceDocuments(wsdl11=<Wsdl11(service_elt=None, service_elt_dict={}, _with_plink=False, root_elt=None, validation_schema=None, namespaces=<odict(_odict__list=['tns']) at remote 0x2075300>, port_type_dict={}, interface=<Interface(_Interface__ns_counter=2, deps={<ComplexModelMeta(_type_info={'string': <type at remote 0x16cd0d0>}, __module__='spyne.model.complex', __orig__=<ComplexModelMeta(_type_info=<TypeInfo(attributes={}, _odict__list=[]) at remote 0x1741fb0>, __module__='spyne.model.complex', _type_info_alt=<TypeInfo(attributes={}, _odict__list=[]) at remote 0x1464d30>, Push=<type at remote 0x1741bc0>, Attributes=<AttributesMeta(__module__='spyne.model.complex', sqla_table_args=None, logged=False, sqla_metadata=None, sqla_table=None, table_name=None, _nullable=None, _variants=<WeakKeyDictionary(_remove=<function at remote 0x1...(truncated)

**Comment by plq** [comment]
My day job involves a lot of C/C++ on desktop and embedded environments and I absolutely have no idea what I'm looking at.

**Comment by juliengreard** [comment]
well, it's the backtrace catched by GDB while the segfault occurs...

**Comment by plq** [comment]
Ok, now I can see through :) While very interesting, this is definitely not a Spyne bug.

I can only assume it's a garbled pointer error, i.e., memory corruption.

You're using WsgiApplication with wsgiref, so the only two suspects for memory corruption are either lxml or CPython itself. Run the same thing within valgrind and see whether any suspicious writes turn up. If it does (it should) then escalate it to whoever's code that's coming from. If not, run memtest or something, I don't know.

The first wsdl request to WsgiApplication involves mutexes, so maybe something's not getting along well with them.

BTW, where ever you go with a gdb backtrace, you'll be asked to attach a core dump. Without one, it's just a very low-chance guesswork. Valgrind has the option to drop to gdb on suspicious activity, you can have a look at that. Probably the segfault is only a symptom of an earlier memory corruption, so you need to catch where memory gets corrupted and not where it segfaults.

Best of luck :8ball: :)

**Comment by plq** [comment]
On close look, this is not a wsdl request, so my comment about mutexes don't apply. It was a long shot anyway.
