### ISSUE TITLE
ByteArray attribute deserializing as a list instead of bytes

### ISSUE THREAD

**Issue by tim-mitchell** [arskom/spyne#430]
Given the following complex type

```
class Project(ComplexModel):
    __namespace__ = 'tns'
    name = Unicode
    thumbnail = ByteArray
```

A service using that type

```
class AService(ServiceBase):
    @rpc(Project, _returns=Boolean)
    def register_project(ctx, project):
        assert type(project.thumbnail) == bytes
```

with

```
    in_protocol = MessagePackRpc()
    out_protocol = MessagePackDocument()
```

The thumbnail attribute is a 1 element list containing the bytes and the assert fails.
Found in development head (2.12)

**Comment by plq** [comment]
ByteArray deserializes to an iterable of str (or bytes in py3) instances. in messagepack rpc, that'd be a list of `str`s

**Comment by plq** [comment]
http://spyne.io/docs/2.10/reference/model/binary.html#spyne.model.binary.ByteArray

**Comment by tim-mitchell** [comment]
Reading the docs carefully I see that you are correct - I guess it just wasn't what I expected.
What spyne type do I use to get a six.binary_type instead of a list of them?

**Comment by plq** [comment]
The plan has always been let bytearray data be read in chunks. so you use it by always iterating over it. There's no such type unless you come up with your own
