### ISSUE TITLE
Value error __class__ is not in list during spyne import

### ISSUE THREAD

**Issue by penoux** [arskom/spyne#432]
Hello,

I had a working SOAP service working under Django 1.7 / Python 2.7 / Spyne 2.11. I am migrating my full application to Python 3.4 and as far as I understand, XML related features should work on Py3.

The application crashes during the import of DjangoView when processing the request (Django starts ok)
- Exception returned is `Value error __class__ is not in list`.
- Exception location is `spyne\util\odict.py in __delitem__, line 68`

The code in odict.py:

``` python
    def __delitem__(self, key):
        if not isinstance(key, int):
            key = self.__list.index(key) # ouch.
```

My urls.py:

``` python
    from django.conf.urls import patterns, url
    from spyne.server.django import DjangoView
    from soap.views import app

    urlpatterns = patterns(
        '',
        url(r'^test/', DjangoView.as_view(application=app), name='test-service'),
    )
```

Any idea on this ? I really appreciate Spyne and would not like to have to seek a new SOAP framework or reimplement everything manually.

**Comment by plq** [comment]
there's not enough information here, please provide full stack traces and/or a minimal script that reproduces the problem

**Comment by plq** [comment]
http://sscce.org/

**Comment by penoux** [comment]
Hello,

To reproduce the issue I created a new, blanck "test_spyne" Django project in Eclipse + Pydev 4.0, Python 3.4.3, Django 1.8.1, Spyne 2.11.0. No model. 
I discovered in fact 2 kinds of exceptions (1 during import while in Pydev Debug mode, 1 during XML parsing in Pydev Run mode).

# views.py
# -*- coding: utf8 -*-
from spyne.service import ServiceBase
from spyne.model.primitive import Unicode
from spyne.model.complex import ComplexModel
from spyne.protocol.soap import Soap11
from spyne.application import Application
from spyne.decorator import rpc

TEST_NS = 'http://test.service.com/'

class Response(ComplexModel):
    __namespace__ = TEST_NS

    _type_info = [
        ('RequestID', Unicode),
        ('AccountID', Unicode),
        ('ReturnCode', Unicode),
        ]

class Test(ServiceBase):
    @rpc(Unicode, Unicode,
         _operation_name='Request',
         _in_variable_names={'request_id': 'RequestID',
                             'account_id': 'AccountID'},
         _out_message_name='RequestResponse',
         _out_variable_name='return',
         _returns=Response,
         _port_type='TestRemote',)
    def request(ctx, request_id, account_id):
        response = Response()
        response.RequestID = request_id
        response.AccountID = account_id
        response.ReturnCode = 'OK'

        return response

app = Application([Test], TEST_NS,
                  'Test',
                  in_protocol=Soap11(validator='lxml'),
                  out_protocol=Soap11(),
                  )

# urls.py
# -*- coding: utf8 -*-
from django.conf.urls import url

from spyne.server.django import DjangoView
from test_spyne.views import app

urlpatterns = [
    url(r'^test/', DjangoView.as_view(application=app),
        name='test')
]

# Request (with SOAPUI)
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:test="http://test.service.com/">
   <soapenv:Header/>
   <soapenv:Body>
      <test:Request>
         <test:RequestID>123456</test:RequestID>
         <test:AccountID>0024700</test:AccountID>
      </test:Request>
   </soapenv:Body>
</soapenv:Envelope>

Test 1: Launch project in Pydev debug mode (Debug as... Pydev Django).
result: HTTP Error 500 from Django
Environment:
Request Method: POST
Request URL: http://localhost:8000/test/

Django Version: 1.8.1
Python Version: 3.4.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'test_spyne')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')

Traceback:

Traceback:
File "C:\Python34\lib\site-packages\django\core\handlers\base.py" in get_response
  119.                 resolver_match = resolver.resolve(request.path_info)
File "C:\Python34\lib\site-packages\django\core\urlresolvers.py" in resolve
  366.             for pattern in self.url_patterns:
File "C:\Python34\lib\site-packages\django\core\urlresolvers.py" in url_patterns
  402.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "C:\Python34\lib\site-packages\django\core\urlresolvers.py" in urlconf_module
  396.             self._urlconf_module = import_module(self.urlconf_name)
File "C:\Python34\lib\importlib\__init__.py" in import_module
  109.     return _bootstrap._gcd_import(name[level:], package, level)
File "C:\Users\PIHE7364\workspace\test_spyne\test_spyne\urls.py" in <module>
  4. from spyne.server.django import DjangoView
File "C:\Python34\lib\site-packages\spyne\__init__.py" in <module>
  34. from spyne.decorator import rpc
File "C:\Python34\lib\site-packages\spyne\decorator.py" in <module>
  40. from spyne.model.complex import ComplexModel
File "C:\Python34\lib\site-packages\spyne\model\__init__.py" in <module>
  123. from spyne.model.binary import File
File "C:\Python34\lib\site-packages\spyne\model\binary.py" in <module>
  35. from spyne.error import ValidationError
File "C:\Python34\lib\site-packages\spyne\error.py" in <module>
  30. class InvalidCredentialsError(Fault):
File "C:\Python34\lib\site-packages\spyne\util\odict.py" in __delitem__
  68.             key = self.__list.index(key) # ouch.

Exception Type: ValueError at /test/
Exception Value: '__class__' is not in list

Test 2: Launch project in Pydev run mode (Run as... Pydev Django).
result: HTTP Error 500 from Django
Environment:
Request Method: POST
Request URL: http://localhost:8000/test/

Django Version: 1.8.1
Python Version: 3.4.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'test_spyne')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')

Traceback:
File "C:\Python34\lib\site-packages\django\core\handlers\base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "C:\Python34\lib\site-packages\spyne\server\django.py" in view
  304.             return self.dispatch(request, *args, **kwargs)
File "C:\Python34\lib\site-packages\django\views\decorators\csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)
File "C:\Python34\lib\site-packages\spyne\server\django.py" in dispatch
  324.         return handler(request, *args, **kwargs)
File "C:\Python34\lib\site-packages\spyne\server\django.py" in post
  330.         return self.server.handle_rpc(request, *args, **kwargs)
File "C:\Python34\lib\site-packages\spyne\server\django.py" in handle_rpc
  120.         contexts = self.get_contexts(request)
File "C:\Python34\lib\site-packages\spyne\server\django.py" in get_contexts
  214.         return self.generate_contexts(initial_ctx, in_string_charset)
File "C:\Python34\lib\site-packages\spyne\server\_base.py" in generate_contexts
  61.             self.app.in_protocol.create_in_document(ctx, in_string_charset)
File "C:\Python34\lib\site-packages\spyne\protocol\soap\soap11.py" in create_in_document
  197.                                                                         charset)
File "C:\Python34\lib\site-packages\spyne\protocol\soap\soap11.py" in _parse_xml_string
  94.     string = b''.join(xml_string)

Exception Type: TypeError at /test/
Exception Value: sequence item 0: expected a bytes-like object, int found

**Comment by plq** [comment]
gosh, please put these in a gist.

https://gist.github.com/

**Comment by penoux** [comment]
Hello,

Thanks, I am a beginner at github/gist issues ;)
I moved snippets as recommended.

**Comment by ulope** [comment]
I'm running into what seems to be the same issue. For me problem only occurs when running under pydev's debugger (through PyCharm, which uses that debugger).

For debugging purposes I patched `spyne.util.odict::odict.__delitem__` to look like this:
```python
    def __delitem__(self, key):
        if not isinstance(key, int):
            try:
                key = self.__list.index(key) # ouch.
            except ValueError:
                import traceback
                traceback.print_stack()
                pass

        super(odict, self).__delitem__(self.__list[key])
        del self.__list[key]
```
This produced [this output](https://gist.github.com/ulope/fba0497c2f3f598f55a4) and allowed my application to run under the debugger. Obviously silently swallowing these exceptions is not a viable solution, but it shows that the exceptions only seem to be triggered during import time of the `Fault` subclasses.

**Comment by penoux** [comment]
Thanks @ulope for the workaround! Using latest 2.12 beta (for better Python3/Django compatibility) + your patch makes things work now.
Any idea how I could monkey patch spyne.util.odict::odict.__delitem__, waiting for an official fix?

**Comment by plq** [comment]
is there a way to integrate the pydev debugger to spyne's test suite?

**Comment by plq** [comment]
please check #458 -- does that branch solve your problems?

**Comment by penoux** [comment]
@plq I saw your fix #458, did not have time to test it though.

Meanwhile I used the excellent wrapt module from G. Dumpleton (http://blog.dscpl.com.au/2015/03/ordering-issues-when-monkey-patching-in.html) to monkey patch ```odict.__delitem__``` at import time in Django settings.py, only if PyDev debugger is active.

Snippet :
```python
# settings.py
from wrapt import register_post_import_hook

def load_and_execute(name):
    def _load_and_execute(target_module):
        __import__(name)
        patch_module = sys.modules[name]
        getattr(patch_module, 'apply_patch')(target_module)
    return _load_and_execute

def is_pydev_debug():
    for frame in inspect.stack():
        if frame[1].endswith("pydevd.py"):
            return True
    return False

if is_pydev_debug():
    register_post_import_hook(load_and_execute('patch_spyne'), 'spyne.util.odict')

# patch_spyne.py
from wrapt import wrap_function_wrapper

def _delitem_wrapper(wrapped, instance, args, kwargs):
    print('executing patch of', wrapped.__name__)
    key = args[0]
    if not isinstance(key, int):
        try:
            key = instance.__list.index(key) # ouch.
        except:
            """
            import traceback
            print("=============================")
            traceback.print_stack()
            """
            return

    super().__delitem__(instance.__list[key])
    del instance.__list[key]

def apply_patch(module):
    print('patching', module.__name__)
    wrap_function_wrapper(module, 'odict.__delitem__', _delitem_wrapper)
```

**Comment by penoux** [comment]
I tried fix #458, I now have another error, the traceback is [here](https://gist.github.com/penoux/bf579a4c49dbcc93790c#file-traceback-py)

**Comment by plq** [comment]
that, as well, should be fixed now

**Comment by penoux** [comment]
Thanks. Import fixed, GET wsdl ok, but another error [here](https://gist.github.com/penoux/082c0f6d488301400b43#file-traceback2_spyne_458-py).
Note : no changes in my code, with 2.12-beta6 + patch odict, everythings works.

**Comment by plq** [comment]
> Thanks. Import fixed, GET wsdl ok, but another error here.

Thanks for your continued help. Is there absolutely no way to run the pydev debugger as a separate interpreter from the command line? Doing it like this makes debugging very time-consuming :disappointed: .

> Note : no changes in my code, with 2.12-beta6 + patch odict, everythings works.

If you refer to @ulope 's patch, it's a hack that swallows exceptions, as can be seen from his traceback log. I'd rather fix those exceptions. I'd imagined the easiest way of doing that would be to switch to python's own ordered dict implementation for python 3, but that didn't work.

So at this time I'm out of options. I can't see values passed to functions in tracebacks and I can't reproduce this bug locally which makes it very hard for me to guess what is causing this bug. Any ideas?

**Comment by penoux** [comment]
I know that running the Pydev debugger (through Eclipse) is time consuming. I don't find a way to run pydevd.py from the command line.

The patch from @ulope that I use is a hack, sure. As the bug is produced at import time (before debugger is up I think), even breakpoints in the monkey patching I made with wrapt are useless.

Is there some kind of dynamic class/methods creation at spyne import time ?
Only suggestion I can make: put relevant prints in ```__delitem__``` method.

**Comment by plq** [comment]
When I said "time-consuming" I meant writing a patch and waiting for your feedback. I wasn't running pydev debugger at all.

however, I have access to pycharm which also seems to use pydev's debugger, so I think I'll be able to fix this soon enough if I can reproduce this on my machine.

**Comment by penoux** [comment]
Ah, ok ;) If you can reproduce it, sure we'll progress quicker! Thanks!

**Comment by plq** [comment]
this is totally pydev's fault. I put in a workaround. please report this issue upstream. close if you're happy with  72542d2.

**Comment by plq** [comment]
apparently, pydev does not expect a class dict to have the `'__class__'` key missing. that's possible when a class has a metaclass that has a `__prepare__` method that returns a custom dict-like object. apparently.

**Comment by penoux** [comment]
Sorry but [72542d2](https://github.com/arskom/spyne/commit/72542d2f316b7d14df5666d4298352974a36ed6e) is not working, same error (at line 77). Perhaps your workaround ```_is_under_pydev_debugger``` is not called early enough...
I encourage you to submit a bug to PyDev through [this link](http://www.pydev.org/faq.html#PyDevFAQ-HowdoIReportaBUG%3F), as I won't be able to explain it correctly (metaclasses are too complex for me atm) and follow the fix.

**Comment by plq** [comment]
`_is_under_pydev_debugger()` is called at the import time of *odict*, way before any other Spyne machinery is imported. If you're getting the same error at line 77, this means you're inside the non-pydev-compatible `__delitem__` function because the block at the end of the odict class would overwrite that function with the one at the bottom of the class.

as you can see, the `_is_under_pydev_debugger()` function is a direct copy of your monkeypatch code, so it should work. 

It actually works here, I can't reproduce the problem anymore. Could you please have a look again maybe with a fresh clone of https://github.com/arskom/spyne ? This patch is already merged upstream.

**Comment by plq** [comment]
if you look at the patch 72542d2f316b7d14df5666d4298352974a36ed6e, you'll see that I'm doing *exactly* what you're doing -- monkeypatching __delitem__ when I detect pydev. So it really should work :)

**Comment by penoux** [comment]
I cloned the latest release, now getting the same error at line 85. I saw your patch, it may not be activated the same way as wrapt ``register_post_import_hook`` does. The workaround may not work at import time, at least in some configurations (Django, Eclipse, PyDev) I suppose :(

**Comment by plq** [comment]
OK, I filed a bug and wrote another patch. https://sw-brainwy.rhcloud.com/tracker/PyDev/616

It takes a different approach -- instead of swallowing the `__delitem__` exception in the odict devel it puts what pydev wants inside the odict that is returned by `ComplexModelMeta.__prepare__`

If that doesn't work for you, well, we have to wait for PyDev guys to fix it.

By the way, this works for me in PyCharm.

**Comment by penoux** [comment]
Thanks for the bug filing. Unfortunately the patch still doesn't work for me (error at line 77 in ``__delitem__``) under Eclipse/Pydev/Django/Spyne. I will keep the wrapt patch for the time being.

**Comment by plq** [comment]
Well, sorry, you're on your own.  If you can come up with a better `is_pydev_debug()` (without import hooks), I'll take your word and accept it.

**Comment by codingjoe** [comment]
What's the status here? I'd really like to use PyCharm's debugger again.

**Comment by penoux** [comment]
Hello,

I am not using Eclipse/Pydev anymore, but Pycharm, where I don’t have the issue.

Regards,

Patrick Enoux

**Comment by codingjoe** [comment]
@penoux wait, you don't have this issue using PyCharm? Any magic tricks I should know? I can't get it working for me :/

**Comment by oldium** [comment]
I faced the exact same issue now. The commit 5fa42b839b5a1f0a988a0c0e544f97c8b93997b7 actually makes things worse, because the __class__ attribute is set wrong - it contains the metaclass type instance instead of the class type instance.

**Comment by plq** [comment]
I'm open to suggestions

**Comment by oldium** [comment]
When I replace `odict` by `dict` in the \_\_prepare__ method (and disable the pydev hack), there is no crash. So it looks like the `odict` implementation does something more than the pure `dict` does.

**Comment by oldium** [comment]
Fixed in pull request #572

**Comment by oldium** [comment]
Just for others - PyDev debugger is now usable on branch `master`. I think this issue could be closed. Maybe merge it to stable branch too?

**Comment by codingjoe** [comment]
I'd certainly would welcome a release that would include this commit 👍

**Comment by orzarchi** [comment]
Any update? Been running unstable master branch for a long time now

**Comment by plq** [comment]
the latest alpha is on pypi, you can use it instead.

**Comment by plq** [comment]
So apparently this is fixed in master? Closing -- reopen if not happy
