### ISSUE TITLE
Spyne.protocol.soap.Soap11 checks for a transport.type value that never gets set to 'wsgi'

### ISSUE THREAD

**Issue by ikelos** [arskom/spyne#446]
In [1] on line 126, spyne.protocol.soap.Soap11 checks for transport.type to be set to 'wsgi'.  I can't find anywhere in the code that would set it to that though (including the WsgiApplication wrapper for spyne apps).  I was testing grafting a spyne WsgiApplciation into a CherryPy app, but a direct request to the endpoint caused the transport to come through as http, which bypasses the check for POST, and the request fails a long time later on with a MemoryError.

It's not clear whether the WsgiTransportContext should set its own type to 'wsgi' or whether the GET check should apply to all http transports?  I had difficulty finding any clear documentation on the use of the transport.type variable.  Any help in getting this resolved would be much appreciated.  If you need any further information please just ask.  Thanks!

[1] https://github.com/arskom/spyne/blob/master/spyne/protocol/soap/soap11.py

**Comment by plq** [comment]
that's an artifact from a long lost time :) thanks a lot for reporting it.

**Comment by plq** [comment]
could you please test the latest patch and let me know whether this resolves this issue?

**Comment by ikelos** [comment]
Hiya, yep that seems to work fine. Thanks!  Happy for you to close this...

**Comment by plq** [comment]
thanks!
