### ISSUE TITLE
Xml Schema does not like slug_re.pattern

### ISSUE THREAD

**Issue by plq** [arskom/spyne#448]
https://travis-ci.org/arskom/spyne/jobs/71332607#L168

**Comment by plq** [comment]
fixed by 0bb3a440904b6a12c28ae17bec43f9d4008b4da9

**Comment by plq** [comment]
@DXist fyi

**Comment by DXist** [comment]
Thanks for adding Django 1.8 support! It's a new LTS release. And Django 1.5 has reached "end of life" so you may drop it from test configuration as well.
