### ISSUE TITLE
multiple services duplicate all operations

### ISSUE THREAD

**Issue by mjrk** [arskom/spyne#450]
Extending the helloworld_soap.py
<pre>
class HelloWorldService2(ServiceBase):
    @rpc(Unicode, Integer, _returns=Iterable(Unicode))
    def say_hello2(ctx, name, times):
        """Docstrings for service methods appear as documentation in the wsdl.
        <b>What fun!</b>

        @param name the name to say hello to
        @param times the number of times to say hello
        @return the completed array
        """

        for i in range(times):
            yield u'Hello, %s' % name

application = Application([HelloWorldService, HelloWorldService2], 'spyne.examples.hello.soap',
                          in_protocol=Soap11(validator='lxml'),
                          out_protocol=Soap11())
</pre>

The resulting WSDL will list

    <wsdl:service name="HelloWorldService">
      <wsdl:port binding="tns:Application" name="Application"><soap:address location="http://localhost:8000/"/></wsdl:port>
    </wsdl:service>
    <wsdl:service name="HelloWorldService2">
      <wsdl:port binding="tns:Application" name="Application"><soap:address location="http://localhost:8000/"/></wsdl:port>
    </wsdl:service>

So, both services have the same type and the same operations. I search and tried but could not find a way to specify each service with its type. Did I miss something?

**Comment by plq** [comment]
I don't see anything??

**Comment by blakev** [comment]
@mjrk What do you expect the WSDL to look like?

**Comment by mjrk** [comment]
As mentioned, I would like to have the HelloWorldService with say_hello and the HelloWorldService2 with say_hello2. Not both services with both operations. Everything would be nice, e.g. having two different address locations etc.:
Maybe I have to register two different applications

**Comment by plq** [comment]
I don't think there's a way to specify port name for a service. patches are welcome
