### ISSUE TITLE
Soap12 stub: unexpected keyword argument 'add_type'

### ISSUE THREAD

**Issue by mjrk** [arskom/spyne#451]
Having a ComplexModel

    class Document(ComplexModel):

        is_important = Unicode(max_len=1)

and using the Soap12 stub, there is an exception for inputs with length > 1:

      File "/home/micha/retresco/zdf-search/env/src/spyne/spyne/server/_base.py", line 122, in get_out_string_pull
        ret = ctx.out_protocol.serialize(ctx, message=ProtocolBase.RESPONSE)
      File "/home/micha/retresco/zdf-search/env/src/spyne/spyne/protocol/soap/soap11.py", line 287, in serialize
        out_body_doc, self.app.interface.get_tns())
      File "/home/micha/retresco/zdf-search/env/src/spyne/spyne/protocol/xml.py", line 463, in to_parent
        return handler(ctx, cls, inst, parent, ns, *args, **kwargs)
    TypeError: schema_validation_error_to_parent() got an unexpected keyword argument 'add_type'

Interestingly, the Soap12 class is not part of the trace.

**Comment by plq** [comment]
fixed. thanks for the report

**Comment by mjrk** [comment]
Cool, awesome!

**Comment by plq** [comment]
> Interestingly, the Soap12 class is not part of the trace.

Soap12 shares a lot of code with Soap11 and XmlDocument, that's why.

**Comment by mjrk** [comment]
Just a small thing. There is still an exception now:

        _append(subelts, E('{%s}Detail' % self.soap_env, inst.detail))
      File "/home/micha/retresco/zdf-search/env/local/lib/python2.7/site-packages/lxml/builder.py", line 227, in __call__
        (type(item).__name__, item))
    TypeError: bad argument type: NoneType(None)

I worked around it by using the same checks like in `fault_to_parent`:


        if isinstance(inst.detail, dict):
            _append(subelts, E('{%s}Detail' % self.ns_soap_env, root_dict_to_etree(inst.detail)))

        elif inst.detail is None:
            pass
        else:
            raise TypeError('Fault detail Must be dict, got', type(inst.detail))

instead of just appending allways. You might want to DRY this up though.

**Comment by plq** [comment]
sorry, where does that code go and how do you reproduce the traceback? can you submit a pull request with a test case?

**Comment by plq** [comment]
oh ok, now i see.

**Comment by mjrk** [comment]
here the PR https://github.com/plq/spyne/pull/9
