### ISSUE TITLE
Investigate too aggressive rounding?

### ISSUE THREAD

**Issue by plq** [arskom/spyne#453]
https://github.com/konradqburst/spyne/commit/d36eee9e2ad88e9d336534aad385c75141c34d68 <= why was this needed?

**Comment by plq** [comment]
@konradqburst I saw your patch d36eee9e2ad88e9d336534aad385c75141c34d68.

I wonder why it was needed? Could you provide me the kind of input that is corrupted by `round()` call?

Please reopen if you want to help. thanks.

**Comment by konradqburst** [comment]
@plq Sometimes I was receiving an error saying "microsecond must be in 0..999999" when spyne was calling "datetime" method from "datetime" module. It was happening inside the spyne's "_parse_datetime_iso_match" method.
I'm sorry, I could create a merge request or make the commit more informative but you know... many projects, lack of time.

**Comment by konradqburst** [comment]
@plq I think it was happening when parsing some input date format with nanosecond precision and I wasn't able to change the received format.
I've just tested this and you can produce the error with datetime(2015, 1, 1, 12, 12, 12, 9999998).
I hope it helps.

**Comment by plq** [comment]
it does! I can now see a traceback. thanks a lot.

**Comment by plq** [comment]
Ok, so first I wanted to round 9999998 microseconds up to one second. That works fine for dates but for times, noone wants to do that because doing arithmetic with times is ill-defined.

so for sake of consistency, microseconds are capped at 999999 and if someone sends in 999999.8 microseconds, the user code gets 999999 microseconds.

However, if somebody sends in 999998.8 microseconds, the user code gets 999999 microseconds again.

This is true for both datetime and time.
