### ISSUE TITLE
A ComplexModel analogous to namedtuple

### ISSUE THREAD

**Issue by Pastafarianist** [arskom/spyne#461]
I have searched in the docs, but found nothing which could help me solve a seemingly simple problem: create ad-hoc classes like namedtuple does. For example, instead of

```python
class Pair(ComplexModel):
    first = String
    second = String
```
I would have something like

```python
Pair = NamedTuple(first=String, second=String)
```

This would allow to write very short function type signatures.

**Comment by plq** [comment]
There's `ComplexModelBase.produce` but that's not what you want because it still requires a key-value mapping of members.

How would the member names in Pair would be generated?

Are you sure you don't need something more like `Array(Unicode, Unicode)` i.e. an array that can have exactly two items, both of them strings?

**Comment by plq** [comment]
And especially in which protocol do you want this? Json? Xml?

**Comment by Pastafarianist** [comment]
@plq I forgot to include the argument names in the `NamedTuple` call. Fixed. It looks like the `ComplexModel.produce` call is a perfect substitute for that. But perhaps it will also be useful to have unnamed fields in a `Tuple`. Something like

    Pair = Tuple(String, String)

You've edited away a remark on `Array(String, String)`, but I'll comment regardless: it doesn't work, the `__new__` call crashes with `TypeError`.

**Comment by plq** [comment]
> You've edited away a remark on Array(String, String), but I'll comment regardless: it doesn't work, the __new__ call crashes with TypeError.

`Array(String, String)` does not exist. I removed that remark because it was exactly what you were suggesting and I think it should actually be called `Tuple` not `Array`.

**Comment by plq** [comment]
So in fact you have what you need with the `produce()` call yes? I'm renaming this issue to just refer to a `Tuple` implementation?

**Comment by plq** [comment]
Or, not. I'm opening a new issue and closing this one.
