### ISSUE TITLE
msgpack debug logging is formatting potentially large strings all the time

### ISSUE THREAD

**Issue by tim-mitchell** [arskom/spyne#471]
in protocols.msgpack lines 189-190 logging strings are formatted regardless of logging level.
in_body_doc can be quite large in real life and can take a few seconds.

        logger.debug('\theader : %r' % (ctx.in_header_doc))
        logger.debug('\tbody   : %r' % (ctx.in_body_doc))

should be

        logger.debug('\theader : %r', ctx.in_header_doc)
        logger.debug('\tbody   : %r', ctx.in_body_doc)

**Comment by plq** [comment]
right. thanks for the heads-up.
