### ISSUE TITLE
Dealing with Binary files as output

### ISSUE THREAD

**Issue by juliengreard** [arskom/spyne#477]
Hello,

I'd like to use Spyne in order to allow the users of my Soap-web-services to download files over HTTP. For instance, I have a "test_file.zip" file on my server and I would like to write a RPC service which returns this file, ie @rpc(_returns = File).

Below is my try:
    
    from spyne.model.binary import File
    @rpc(_returns = File)
    def get_file_test(ctx): 
        value = File.Value(name = "tutu.zip", path = "/path/to/my/file/tutu.zip", type = "application\zip")
        return File().to_base64(value)

This returns me 

    <soap11env:Envelope xmlns:tns="something" xmlns:soap11env="http://schemas.xmlsoap.org/soap/envelope/">
       <soap11env:Body>
          <tns:get_file_testResponse>
                  <tns:get_file_testResult>UEsDBBQAAAAIAC+AY0e4XHS6cgEAAFEEAAAIABwAdG90by5jc3ZVVAkAA0rMOFbFToJWdXgLAAEE6gMAAATqAwAArVDLTsMwELwj8RlIrZRGaztxSE6UFlEESBWFs2USFyzlUSUuIL4eh6Sx3ZZDJQ77mN3x7noyroRX84KtayFYIXhpIWkD/uXJslG8VCyveNZx3YrcL+g3WcZU2pH7VA5Z1y6qTOTeRtSpKBV/E2wtc9GwaiNKkXnpZtsz+Ieo27bZ7lbkfkGPb89vPvnG/KxD0gaa127ZnbnLpUk1o3xlaVXru345Bkkb9BtVpXhuVvZQOqj7+7YR2SBOB6SV9/MMyyBpg/4HlobmydGG/KOuBzUFr9X5GQYUThCaAGEoTEKUhMSPY4gQ8eJQ57AXwKfYciTSNeMWUvH0XbLFfBVhAhiuH6Y0wJ4PeuKFd1cqkY+exmymdRw9P46ZjCaYAtyz2fKFXTHiB3C7+Nazg8hxMFiAHHdpGaKA6ZFII9cFETkI2EeDLaer1c3c1YYmgBLSXoMAxV5MUdyK4gTdxZY7QRs4SZsQOe5/tYHDgHw82E6bH1BLAQIeAxQAAAAIAC+AY0e4XHS6cgEAAFEEAAAIABgAAAAAAAEAAAC0gQAAAAB0b3RvLmNzdlVUBQADSsw4VnV4CwABBOoDAAAE6gMAAFBLBQYAAAAAAQABAE4AAAC0AQAAAAA=</tns:get_file_testResult>
          </tns:get_file_testResponse>
       </soap11env:Body>
    </soap11env:Envelope>

Instead of returning me the zip file as attachment of the SOAP response. What am I doing wrong? I probably didn't understand at all how it should work...

**Comment by plq** [comment]
spyne does not support mtom. there is a half complete implementation but it s not being used. patches are welcome

On 29 December 2015 12:43:43 EET, juliengreard <notifications@github.com> wrote:
>Hello,
>
>I'd like to use Spyne in order to allow the users of my
>Soap-web-services to download files over HTTP For instance, I have a
>"test_filezip" file on my server and I would like to write a RPC
>service which returns this file, ie @rpc(_returns = File)
>
>Below is my try:
>    
>    from spynemodelbinary import File
>    @rpc(_returns = File)
>    def get_file_test(ctx): 
>value = FileValue(name = "tutuzip", path = "/path/to/my/file/tutuzip",
>type = "application\zip")
>        return File()to_base64(value)
>
>This returns me 
>
><soap11env:Envelope xmlns:tns="something"
>xmlns:soap11env="http://schemasxmlsoaporg/soap/envelope/">
>       <soap11env:Body>
>          <tns:get_file_testResponse>
><tns:get_file_testResult>UEsDBBQAAAAIAC+AY0e4XHS6cgEAAFEEAAAIABwAdG90by5jc3ZVVAkAA0rMOFbFToJWdXgLAAEE6gMAAATqAwAArVDLTsMwELwj8RlIrZRGaztxSE6UFlEESBWFs2USFyzlUSUuIL4eh6Sx3ZZDJQ77mN3x7noyroRX84KtayFYIXhpIWkD/uXJslG8VCyveNZx3YrcL+g3WcZU2pH7VA5Z1y6qTOTeRtSpKBV/E2wtc9GwaiNKkXnpZtsz+Ieo27bZ7lbkfkGPb89vPvnG/KxD0gaa127ZnbnLpUk1o3xlaVXru345Bkkb9BtVpXhuVvZQOqj7+7YR2SBOB6SV9/MMyyBpg/4HlobmydGG/KOuBzUFr9X5GQYUThCaAGEoTEKUhMSPY4gQ8eJQ57AXwKfYciTSNeMWUvH0XbLFfBVhAhiuH6Y0wJ4PeuKFd1cqkY+exmymdRw9P46ZjCaYAtyz2fKFXTHiB3C7+Nazg8hxMFiAHHdpGaKA6ZFII9cFETkI2EeDLaer1c3c1YYmgBLSXoMAxV5MUdyK4gTdxZY7QRs4SZsQOe5/tYHDgHw82E6bH1BLAQIeAxQAAAAIAC+AY0e4XHS6cgEAAFEEAAAIABgAAAAAAAEAAAC0gQAAAAB0b3RvLmNzdlVUBQADSsw4VnV4CwABBOoDAAAE6gMAAFBLBQYAAAAAAQABAE4AAAC0AQAAAAA=</tns:get_file_testResult>
>          </tns:get_file_testResponse>
>       </soap11env:Body>
>    </soap11env:Envelope>
>
>Instead of returning me the zip file as attachment of the SOAP response
>What am I doing wrong? I probably didn't understand at all how it
>should work
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/arskom/spyne/issues/477

-- 
Sent from my mobile. Pardon the brevity.

**Comment by juliengreard** [comment]
1- There is no way to use attachment without mtom ? I mean, if I don't care about the size of the response?
2- Can't I just use the Base64 encoding even if it's larger ? Can it work for a zip file?

**Comment by plq** [comment]
base64-encoded binary data should work. you must return the File.Value instance though.

**Comment by plq** [comment]
if you return a base64 encoded string, it will be encoded once more to base64, which is most probably not what you want

**Comment by juliengreard** [comment]
Ok thanks for the answer. I tryed the following:

    @rpc(_returns = File)
    def get_file_test(ctx):
        with open("/path/to/my/file.zip", "rb") as data:
            value = File.Value(name = "file.zip", 
                               path = "/path/to/my/file.zip", 
                               type = "application\zip", 
                               data = data.read())
        return value

I get the following error : 

      Traceback (most recent call last):
       File "/usr/local/lib/python2.7/dist-packages/spyne/util/__init__.py", line 120, in start
    next(ret)
        File "/usr/local/lib/python2.7/dist-packages/spyne/protocol/xml.py", line 782, in _get_members_etree
    sub_name)
        File "/usr/local/lib/python2.7/dist-packages/spyne/protocol/xml.py", line 463, in to_parent
    return handler(ctx, cls, inst, parent, ns, *args, **kwargs)
        File "/usr/local/lib/python2.7/dist-packages/spyne/protocol/xml.py", line 616, in modelbase_to_parent
    elt.text = self.to_unicode(cls, inst)
        File "lxml.etree.pyx", line 953, in lxml.etree._Element.text.__set__ (src/lxml/lxml.etree.c:44956)
        File "apihelpers.pxi", line 677, in lxml.etree._setNodeText (src/lxml/lxml.etree.c:20273)
        File "apihelpers.pxi", line 1395, in lxml.etree._utf8 (src/lxml/lxml.etree.c:26485)
      ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

**Comment by plq** [comment]
Thanks for reporting this.

**Comment by plq** [comment]
could you please confirm e7d575f fixes your issue?

**Comment by juliengreard** [comment]
Yes, it is working like a charm ! Thanks you :-)
The fix will be part of the master branch right? Then it will be available on the 2_13 release? Can't it be part of the 2_12?

**Comment by plq** [comment]
Don't worry, I'm not planning to wait another 11 months for 2.13 :)

**Comment by plq** [comment]
You did see the example, yes? That's how you're supposed to use it to send files which you already don't have the file handle.

https://github.com/arskom/spyne/commit/e7d575fc24c6a2147d9a775fec3753e0006c13f0#diff-9e488be4d5886464de37511eb2e9652dR47

If you already have the file handle, (i.e. whatever `open()` returns) you can return `File.Value(handle=handle)` to avoid allocating another fd.

**Comment by juliengreard** [comment]
Yes I saw it ! Thanks for adding it to the examples, it's very usefull :-) 

My service looks like the following:

    @rpc(_returns = File)
    def get_file_test(ctx):
        with open("my_file", "rb") as handle:
            return File.Value(handle = handle)

And on the client's side:

    encoded = base64.b64decode(request_result)
    with open("my_file_result","wb") as file:
        file.write(encoded)

And it works, with a very little amount of line of code ! I hope it will help someone else.

**Comment by plq** [comment]
Ok, why are you not doing `File.Value(path="my_file")` ?

**Comment by juliengreard** [comment]
Because the service I wrote above is a simplification of what I really did, but yes, you are right.
Do you already know when the 2.13 will be out ? I don't need a precise date, just an approximate date, in order to plan my developments

**Comment by plq** [comment]
> Because the service I wrote above is a simplification of what I really did, but yes, you are right.

Please note that in your example, the file handle you pass to the File.Value instance is closed once the function returns. So you're returning a closed handle to Spyne.

In fact, when I try your example, it doesn't work:

```
ERROR:spyne.util:I/O operation on closed file
Traceback (most recent call last):
  File "/home/plq/src/github/plq/spyne/spyne/util/__init__.py", line 120, in start
    next(ret)
  File "/home/plq/src/github/plq/spyne/spyne/protocol/xml.py", line 782, in _get_members_etree
    sub_name)
  File "/home/plq/src/github/plq/spyne/spyne/protocol/xml.py", line 463, in to_parent
    return handler(ctx, cls, inst, parent, ns, *args, **kwargs)
  File "/home/plq/src/github/plq/spyne/spyne/protocol/xml.py", line 616, in modelbase_to_parent
    elt.text = self.to_unicode(cls, inst)
  File "/home/plq/src/github/plq/spyne/spyne/protocol/_outbase.py", line 211, in to_unicode
    return handler(class_, value, *args, **kwargs)
  File "/home/plq/src/github/plq/spyne/spyne/protocol/_outbase.py", line 455, in file_to_unicode
    return self.file_to_string(cls, value, suggested_encoding)
  File "/home/plq/src/github/plq/spyne/spyne/protocol/_outbase.py", line 421, in file_to_string
    fileno = value.handle.fileno()
ValueError: I/O operation on closed file
```

**Comment by juliengreard** [comment]
In fact, when I try your example, it doesn't work:

Yes, I just edited my example with a working sample ^^ it's less confusing this way
