### ISSUE TITLE
Annotations mising from the wsdl

### ISSUE THREAD

**Issue by plq** [arskom/spyne#480]
Moving @yundatm's original bug here: https://github.com/spyne/spyne.github.com/issues/9

--------

Hi there,
after upgrading to the latest spyne (2.12.11), the WSDL document lost all the annotations.
I found the bug and the fix is easy. In spyne/interface/xml_schema/model.py on line 256 replace

```
            doc.text = doc_text
```

with

```
            doc.text = v_doc_text
```

That fixes it.
Just to give you the context, this is the code in model.py:

```
        v_doc_text = v.get_documentation()
        if v_doc_text:
            # Doesn't support multi-language documentation
            annotation = etree.SubElement(member, XSD('annotation'))
            doc = etree.SubElement(annotation, XSD('documentation'))
            doc.text = doc_text     <-------- this is the bug, should be v_doc_text
```

Could you please make this change in the code base so it's fixed for next version?

Thanks,
Martin.

**Comment by plq** [comment]
Thanks a lot for reporting this. I'm surprised this was not cought by the test case though. Do you have a test case handy?

**Comment by plq** [comment]
@yundatm

**Comment by yundatm** [comment]
Yes, just define any field that has an annotation, e.g. this:
map_name = Unicode(doc="The name of an existing map to be included in this order")
due_date = DateTime(doc="Defaults to today if not specified")
and the wsdl won't have the annotations.

**Comment by yundatm** [comment]
Forgot to mention - the above is part of a ComplexModel definition:
class OrderProductStruct(ComplexModel):
    map_name = Unicode(doc="The name of an existing map to be included in this order")
    due_date = DateTime(doc="Defaults to today if not specified")

**Comment by plq** [comment]
you need to learn github formatting mate.

**Comment by plq** [comment]
ok, that's enough for me to build a test case. thanks a lot.

**Comment by plq** [comment]
ok, closing this. please reopen if not happy. thanks again!

**Comment by yundatm** [comment]
Thank you! :-)
