### ISSUE TITLE
Converting DateTime objects to String if year is below 1900

### ISSUE THREAD

**Issue by konradqburst** [arskom/spyne#483]
Hi @plq 
I've encountered an issue in some older version of your library while converting dates to string with year below 1900.
I'm not sure if the issue occurs in the newest version of spyne but I can see that it's still using strftime method (which is causing the issue) in a few places.
You can check how I've fixed it here:
https://github.com/konradqburst/spyne/commit/7bc8434bd33f8567ae8143f053f139b71dc9afcd

More info on this http://stackoverflow.com/a/32206673 or http://code.activestate.com/recipes/306860-proleptic-gregorian-dates-and-strftime-before-1900/

I don't have spare time to check if the issue occurs in the latest spyne version so I'm sorry if the bug does no longer occur and then you are free to delete this report.

**Comment by plq** [comment]
Well, you're spot on. Thanks for the heads-up.

**Comment by plq** [comment]
`.isoformat()` is just happy with ancient datetimes, that's how this bug could hide for so long.
