### ISSUE TITLE
Travis build failing?

### ISSUE THREAD

**Issue by hartwork** [arskom/spyne#486]
Hi!

Have you noticed that Travis reports the build to fail?
https://travis-ci.org/arskom/spyne/builds

Best, Sebastian

**Comment by plq** [comment]
Yes but all tests pass, its just the latest versions of tox and pip cant get along. Theres nothing i can do and o wont do bogus commits just to turn that light to green.
-- 
Sent from my mobile. Pardon the brevity.

**Comment by hartwork** [comment]
I see. Those who can do something, do they know about the issue?

**Comment by plq** [comment]
Yes, I remember the bug reports were already filed for both projects. I don't know whether it's fixed. The issue is pip removing the --download-cache option.
