### ISSUE TITLE
Python RPC client half?

### ISSUE THREAD

**Issue by hartwork** [arskom/spyne#487]
Hi!

Compared to the http://www.zerorpc.io/ main page, the example combinator of Spyne is more flexibale but lacks Python RPC client code. Is there a Python client side with Spyne? (I am looking for/at alternatives to https://docs.python.org/2/library/xmlrpclib.html).

Best, Sebastian

**Comment by plq** [comment]
Dear sebastian,

first, thanks for your recent interest in Spyne. But the issue tracker is only for reporting issues, not asking questions. Please use the ml or so for that.

http://spyne.io/new has all the links.

Thanks
Burak

**Comment by hartwork** [comment]
I was expecting my tickets to be or end up as bug reports. On this very ticket, I was expecting that a client exists but that the docs make it too hard to find it. That would have been a bug. Nevermind.

**Comment by wingyiu** [comment]
@hartwork http://github.com/wingyiu/py-svrkit
