### ISSUE TITLE
Spyne creates invalid xml-schema if dirived class implements a xml attribute.

### ISSUE THREAD

**Issue by ve-i-uj** [arskom/spyne#491]
First of all, I want to thank you for easy-to-use and well-read library.

Problem:

I need to realize existing WSDL. I try to inherit my complex type class. But when the derived class implements a xml-attribute I get an error  'The content is not valid.'. I get spyne created xsd file and look that derived class in xsd file has realy invalid defenition.
Xml attribute of derived class should be in 'xs:extension' tag but not in 'xs:complexType' tag.

(spyne version '2.12.11', python 2.7.9)

Thanks.

Code:

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-

    from spyne.model.primitive import Unicode
    from spyne.server.wsgi import WsgiApplication
    from spyne.protocol.soap.soap12 import Soap12
    from spyne.model.complex import XmlAttribute, ComplexModel
    from spyne import Application, rpc, ServiceBase

    ADDRESS = '127.0.0.1'
    PORT = 8070

    class DeviceEntity(ComplexModel):
        Example = Unicode

    class DigitalInput(DeviceEntity):
        Example2 = Unicode
        IdleState = XmlAttribute(Unicode)

    class Service(ServiceBase):

        @rpc(_returns=DigitalInput, _body_style='bare')
        def GetDigitalInput(ctx):
        return DigitalInput()

    application = Application([Service], 'some_tns',
                                in_protocol=Soap12(validator='lxml'),
                                out_protocol=Soap12())

    wsgi_application = WsgiApplication(application)

    if __name__ == '__main__':
        from wsgiref.simple_server import make_server
        server = make_server(ADDRESS, PORT, wsgi_application)
        server.serve_forever()

Error:    

    Traceback (most recent call last):
      File "/home/leto/workspace/spyne_test/inherited_classes.py", line 32, in <module>
        out_protocol=Soap12())
      File "/usr/local/lib/python2.7/dist-packages/spyne/application.py", line 113, in __init__
        self.in_protocol.set_app(self)
      File "/usr/local/lib/python2.7/dist-packages/spyne/protocol/xml.py", line 368, in set_app
        xml_schema.build_validation_schema()
      File "/usr/local/lib/python2.7/dist-packages/spyne/interface/xml_schema/_base.py", line 223, in build_validation_schema
        self.validation_schema = etree.XMLSchema(etree.parse(f))
      File "xmlschema.pxi", line 90, in lxml.etree.XMLSchema.__init__ (src/lxml/lxml.etree.c:175129)
    lxml.etree.XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}complexType': The content is not valid. Expected is (annotation?, (simpleContent | complexContent | ((group | all | choice | sequence)?, ((attribute | attributeGroup)*, anyAttribute?))))., line 16

Spyne created xsd file:

    <xs:schema xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:tns="some_tns" xmlns:plink="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:soap12env="http://www.w3.org/2003/05/soap-envelope" xmlns:soap11env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap12enc="http://www.w3.org/2003/05/soap-encoding" xmlns:soap11enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="some_tns" elementFormDefault="qualified">
      <xs:complexType name="GetDigitalInput"/>
      <xs:complexType name="DeviceEntity">
        <xs:sequence>
          <xs:element name="Example" type="xs:string" minOccurs="0" nillable="true"/>
        </xs:sequence>
      </xs:complexType>
      <xs:complexType name="DigitalInput">
        <xs:complexContent>
          <xs:extension base="tns:DeviceEntity">
            <xs:sequence>
              <xs:element name="Example2" type="xs:string" minOccurs="0" nillable="true"/>
            </xs:sequence>
          </xs:extension>
        </xs:complexContent>
        <xs:attribute name="IdleState" type="xs:string"/>
      </xs:complexType>
      <xs:element name="GetDigitalInput" type="tns:GetDigitalInput"/>
      <xs:element name="DeviceEntity" type="tns:DeviceEntity"/>
      <xs:element name="GetDigitalInputResponse" type="tns:DigitalInput"/>
    </xs:schema>

Attribute 'IdleState' of class DigitalInput should be in 'xs:extension' tag but not in 'xs:complexType' tag.

**Comment by ashleysommer** [comment]
I'm seeing the same problem.
When googling for the answer, I found a stack-overflow issue about it too.
http://stackoverflow.com/questions/36997217/spyne-error-when-inheriting-from-a-complex-type-and-derived-class-implements-a/37783711#37783711
I replied on that page, but I will reply in here too.

Here is the .xsd file that spyne generated in my `/tmp/` dir.
```
<xs:schema xmlns:plink="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:s0="http://www.opengis.net/ows/1.1" xmlns:s1="spyne.model.primitive.string" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap11enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap11env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap12enc="http://www.w3.org/2003/05/soap-encoding" xmlns:soap12env="http://www.w3.org/2003/05/soap-envelope" xmlns:tns="http://www.opengis.net/sos/2.0" xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://www.opengis.net/sos/2.0" elementFormDefault="qualified">
  <xs:import namespace="http://www.opengis.net/ows/1.1" schemaLocation="s0.xsd"/>
  <xs:complexType name="CapabilitiesType">
    <xs:complexContent>
      <xs:extension base="s0:CapabilitiesBaseType"/>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="GetCapabilitiesType">
    <xs:complexContent>
      <xs:extension base="s0:GetCapabilitiesType"/>
    </xs:complexContent>
    <xs:attribute name="service" type="xs:string"/> <!--HERE-->
  </xs:complexType>
  <xs:element name="Capabilities" type="tns:CapabilitiesType"/>
  <xs:element name="GetCapabilities" type="tns:GetCapabilitiesType"/>
</xs:schema>
```
It is actually an invalid xsd schema file, and throws that same error when the application runs.

You can see on the line that I highlighted with `<!--HERE-->` that `xs:attribute` tag is in the wrong spot. It should be two lines up, inside the `xs:extension` element, like this:
```
<xs:complexType name="GetCapabilitiesType">
    <xs:complexContent>
      <xs:extension base="s0:GetCapabilitiesType">
        <xs:attribute name="service" type="xs:string"/> <!--HERE-->
      </xs:extension>
    </xs:complexContent>
</xs:complexType>
```

**Comment by ve-i-uj** [comment]
I found the bug place in code of spyne library which leads to this issue. I changed several code lines in library to solve problem and It helped in my case. I hope it will be usefull for anybody who has the same problem.
(I changed spyne library !!! VERSION '2.13.0' !!!)

File path spyne/interface/xml_schema/model.py, `complex_add` method, this code part:

    _ext_elements = dict()
    for k,v in deferred:
        ao = v.attribute_of
        if ao is None:
            attribute = etree.Element(XSD('attribute'))
            xml_attribute_add(v, k, attribute, document)
            if cls.Attributes._xml_tag_body_as is None:
                #===============================================================
                # MY HACK
                #===============================================================
#                 complex_type.append(attribute) # <-- I just commented out this line
                extension.append(attribute) # <-- and added this line. That's all
                
            else:
                xtba_ext.append(attribute)
            continue

**Comment by ashleysommer** [comment]
I actually did a very similar fix today to fix my problem.

The difference with my fix is that I changed that line to:
sequence_parent.append(attribute)

That is more correct because sequence_parent can point to either extension
if it is a subtype element, or complex_type if it is a normal element, so
the attribute is added to the correct node either way.

**Comment by ashleysommer** [comment]
Created a PR with the fix: https://github.com/arskom/spyne/pull/493

**Comment by plq** [comment]
indeed it does. thanks!

**Comment by tynarasimhareddy** [comment]
Hi,
I am looking for this fix. which release i should take? 
And where i can found the release details which are ongoing/beta phase?

**Comment by plq** [comment]
`pip install -e git://github.com/arskom/spyne.git@spyne-2.13.0-alpha#egg=spyne`

**Comment by tynarasimhareddy** [comment]
Thanks Burak Arslan,
What is the plan on spyne-2.13 release? when is it planned to release?

**Comment by plq** [comment]
this is an issue tracker, please use the mailing list for further info
