### ISSUE TITLE
Serializing an AnyXML type to XML output in Python3 raises NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by ashleysommer** [arskom/spyne#528]
In spyne master branch, in file `src/spyne/spyne/protocol/xml.py`
In the function `any_xml_parent()`,
The line 
```
if isinstance(inst, str) or isinstance(inst, unicode):
```
obviously there is no unicode in python3, this needs to be fixed and a test added to ensure serializing AnyXML type does not crash.

**Comment by plq** [comment]
Thanks a lot for bringing it to my attention. This is fixed in latest master
