### ISSUE TITLE
UnicodeDecodeError when installing spyne==2.12.14 on a Docker container

### ISSUE THREAD

**Issue by rahmonov** [arskom/spyne#532]
I am trying to install spyne 2.12.14 on ubuntu 16.04 docker image:

     pip install spyne==2.12.14

 and getting this:

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0gzdjq91/spyne/setup.py", line 51, in <module>
        LONG_DESC += "\n\n" + open('CHANGELOG.rst', 'r').read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 1895: ordinal not in range(128)

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0gzdjq91/spyne/

Maybe my base image does not have something. Do I need to install something in the system?

**Comment by plq** [comment]
hello,

just pushed a patch to the 2_12 branch for you. can you try 

    pip install git+https://github.com/arskom/spyne@2_12

and let me know whether this works?

best,

**Comment by rahmonov** [comment]
Hi @plq. Thanks for your help.

I solved this by adding the following to the Dockerfile:

    ENV LANG en_US.UTF-8
    RUN locale-gen en_US
    RUN locale-gen en_US.UTF-8
    COPY ./locale /etc/default/locale
    RUN update-locale

Basically by generating en_US locale and updating it.

Which one of the solutions do you think is better?

**Comment by plq** [comment]
In the context of containers (aka single-purpose OS distributions) yours is a legitimate fix as well.

However, I'd be grateful to you if you tested whether the patch does help. The may be cases where such system-wide changes is not an option.

**Comment by rahmonov** [comment]
Hey @plq, sorry for the late response.
Tried to do `pip install git+https://github.com/arskom/spyne@2_12` but got the same error:
![image](https://cloud.githubusercontent.com/assets/9026972/26724494/21fd2bae-47b3-11e7-94b2-b77921672a5b.png)

**Comment by themylogin** [comment]
@plq @rahmonov replacing `'r'` with `'rb'` (like it is in master) helped me

**Comment by plq** [comment]
ah thanks. just pushed another patch. reopen if not happy.
