### ISSUE TITLE
any way to use＜xsd:all＞on WSDL file ?

### ISSUE THREAD

**Issue by thecdd** [arskom/spyne#534]
May i know any way to use `<xsd:all>` to replace `<xsd:sequence>` on spyne generated WSDL file?

if my wsdl file as the below:
```
<xsd:sequence>
           <xsd:element name="firstName" type="xsd:string"/>
           <xsd:element name="lastName" type="xsd:string"/>
</xsd:sequence>
```
this request is correct:
```
<firstName>first name</firstName>
<lastName>first name</lastName>
```
this request is incorrect (by `in_protocol=Soap11(validator='lxml')`):
```
<lastName>first name</lastName>
<firstName>first name</firstName>
```

Because of the `<xsd:sequence>`, the request must keep the sequence.
But I don't want the sequence limitation for my usage, and seems no API for` <xsd:all>`.

any way to use `<xsd:all>` ?

thank you very much.

**Comment by plq** [comment]
this is not a forum for questions
