### ISSUE TITLE
Soap11 doesn't handle multipart/related

### ISSUE THREAD

**Issue by hylandm** [arskom/spyne#541]
When submitting a multipart/related it is attempted to be collapsed into a application/soap+xml request with collapse_swa in protocol/soap/mime.py. This function takes in the content_type from the HTTP request and the body of the request. It then attempts to parse the envelope using message_from_string without the boundary information that was passed into collapse_swa in the first argument. It fails to divide the message into parts and thus fails to parse the request.

**Comment by plq** [comment]
Hey, thanks for the report. 

I won't have time to work on SOAP bits in the foreseeable future, so feel free to send a pull request or provide more information to make next person's job job easier.

Best,

**Comment by bumblebeey** [comment]
I think i am on same issue :(

**Comment by bumblebeey** [comment]
any one can tell me how can i use multipart/related request ?
i need urgently help

**Comment by plq** [comment]
#601 fixes this as well.
