### ISSUE TITLE
Handling of multiple Iterables broken in spyne 2.10

### ISSUE THREAD

**Issue by totycro** [arskom/spyne#548]
I'm still using spyne 2.10 where I experience the following behavior:

If there are at least 2 Interables with different type parameters in my interface, the wsdl will contain only one Iterable type:

```
<xs:complexType name="functionAResponse">
<xs:sequence>
<xs:element name="functionAResult" type="tns:Iterable" minOccurs="0" nillable="true"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="functionBResponse">
<xs:sequence>
<xs:element name="functionBResult" type="tns:Iterable" minOccurs="0" nillable="true"/>
</xs:sequence>
```

It appears that for generating the type ```tns:Iterable```, the first type parameter for iterable is written in the wsdl, in this case for an Iterable of ```mydata```:
```
<xs:complexType name="Iterable">
<xs:sequence>
<xs:element name="mydata" type="tns:mydata" maxOccurs="1000"/>
</xs:sequence>
</xs:complexType>
```

The correct behavior would be to generated in this example 2 different result types, as also happens for Arrays.

This bug can also be avoided when specifying a ```typename``` explicitly for the Iterable.

I don't know if this bug still occurs in the latest version.

**Comment by plq** [comment]
please test with the latest version
