### ISSUE TITLE
Body style BARE and inherited subtype (with no member added)

### ISSUE THREAD

**Issue by mthu** [arskom/spyne#552]
We have methods with the common set of arguments, so I defined. 

```
class CommonEntityInput(ComplexModel):
    _type_info = [
        ("Timestamp", DateTime),
        ("Entity", String),
    ]

class InsertEntity(CommonEntityInput):
     pass

class DeleteEntity(CommonEntityInput):
     pass
```
I want to have different types for each method.
I cannot use these subtypes with a BARE body style, causing following error:
`Exception: body_style='bare' does not allow empty model as param`.

Yes, I can copy the _types_info list to each subclass (and remove the superclass) but it will produce different WSDL....

If I remove the check inside the rpc decorator, everything seems to be working .... tested with 2.12.14.

**Comment by plq** [comment]
bare function with empty class should be the same thing as a function without parameters.

**Comment by plq** [comment]
questions go to the mailing list. this is not a bug report.
