### ISSUE TITLE
django: access user data inside rpc method

### ISSUE THREAD

**Issue by patroqueeet** [arskom/spyne#553]
dear, I'm attempting a soaplib1.0 upgrade to spyne. I realized the `@rpc` decorator changed and we now have class_method behavior behind without the App being instantiated. I tried to figure out how to access the auth'd user obj inside the `@rpc` methods but failed. can you quickly point to into the right direction?

many thanks in advance!

**Comment by plq** [comment]
questions go to the mailing list
