### ISSUE TITLE
Not compatible with Python 3.7

### ISSUE THREAD

**Issue by sscherfke** [arskom/spyne#560]
The NullServer uses uses the `async` keyword argument which is a keyword in Python 3.7 and will thus no longer work.

**Comment by plq** [comment]
thanks a lot for the heads-up. fixed in master.

**Comment by plq** [comment]
reopen if not happy

**Comment by sscherfke** [comment]
Thx, looks good.  Is there an ETA for a new release?

**Comment by artxki** [comment]
Please update in PyPI :package:

**Comment by plq** [comment]
This was fixed in april, last release on pypi is in May 10th. Where's the problem?

**Comment by terrycong** [comment]
@sscherfke @artxki Actually you can upgrade to a pre-release version to adopt the feature
 such as :
pip install spyne==2.13.2a0

**Comment by hingehe** [comment]
ModuleNotFoundError: No module named 'lxml'
