### ISSUE TITLE
Question: Order of fields in Spyne WSDL

### ISSUE THREAD

**Issue by lnjuanj** [arskom/spyne#566]
Hi,
I have been investigating through:
https://github.com/arskom/spyne/issues/351 and https://github.com/arskom/spyne/pull/343
... since I just found that the WSDL that Spyne creates has its elements with a different order than I introduced.
I'm using Python 2.7
Since the discussions were previous to the release of version 2.11, I would like to know whether declaring ordered fields would be possible. And, if it's not asking too much, how would I define them.

My example:
class myClass(ComplexModel):
    field1 = Unicode
    field2 = DateTime
    field3 = Unicode(20)

This generates a WSDL with the fields:
<xs:element name="field1" type="xs:string" minOccurs="0" nillable="true"/><xs:element name="**field3**" type="tns:idTagInfo_parentIdTagType" minOccurs="0" nillable="true"/><xs:element name="**field2**" type="xs:dateTime" minOccurs="0" nillable="true"/>

**Comment by plq** [comment]
http://spyne.io/docs/2.10/manual/03_types.html#complex
see predictable field order

this is the issue tracker it's not for questions. there is the mailing list for that.
