### ISSUE TITLE
<soap:binding> tag is missing the correct value for the transport attribute

### ISSUE THREAD

**Issue by oldium** [arskom/spyne#571]
I have found a possible issue - in the following code branch

https://github.com/arskom/spyne/blob/b8925ee5dc407eb9e2a8d97047f14b10425ee01d/spyne/interface/wsdl/wsdl11.py#L476-L477

I miss setting of 'transport' attribute of binding, like few lines below:

https://github.com/arskom/spyne/blob/b8925ee5dc407eb9e2a8d97047f14b10425ee01d/spyne/interface/wsdl/wsdl11.py#L490-L492

**Comment by plq** [comment]
I don't really understand what you mean, can you elaborate please?

**Comment by oldium** [comment]
The result of an error is the following WSDL document fragment:

```
<wsdl:binding name="SubregCzService" type="tns:SubregCzService">
  <soap:binding style="document"/>
   ...
```

when using service definition

```
class SubregCzService(ServiceBase):
    __port_types__ = ("SubregCz",)
   ...
```

instead of expected

```
<wsdl:binding name="SubregCzService" type="tns:SubregCzService">
   <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
   ...
```

**Comment by plq** [comment]
So the binding tag is missing the correct value for the transport attribute?

**Comment by oldium** [comment]
Yes, the `transport` attribute is missing when the code goes this particular "if" branch.
