### ISSUE TITLE
does spyne support ipv6?

### ISSUE THREAD

**Issue by UlissesJr** [arskom/spyne#580]
The service created by ipv6 cannot be accessed ,how to setting the socket?

**Comment by plq** [comment]
questions go to the mailing list or stackoverflow.

**Comment by RunningFaster** [comment]
`class WSGIServerV6(WSGIServer):
    import socket
    address_family = socket.AF_INET6

# 显示声明一下wsgi的address_family
server = make_server('::', conf_dict['listen_port'], drmsauRoot, server_class=WSGIServerV6)
`
