### ISSUE TITLE
multipart xom attachment save corrupted

### ISSUE THREAD

**Issue by bumblebeey** [arskom/spyne#602]
hi new alpha version saving document with problems,
when i try unzip saved attachment getting following error 👍 

```
Archive:  54F34B9C-4B7F-49E3-91BD-3DE438A6919E.zip
warning [54F34B9C-4B7F-49E3-91BD-3DE438A6919E.zip]:  4 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  4
  (attempting to re-compensate)
  inflating: 54F34B9C-4B7F-49E3-91BD-3DE438A6919E.xml
  error:  invalid compressed data to inflate
```

i am logged collapse_swa function in mime type in line 150

```
    msg_string = generator.NL.encode('ascii').join(msg_string)
    logger.info("msg_string  %r" % msg_string)
```

and part of  request
```
Content-Type: application/octet-stream\r\nContent-Transfer-Encoding: binary\r\nContent-ID: <04dfbca1-54b8-4631-a556-4addea6716ed-231373@cxf.apache.org>\r\n\r\nPK\x03\x04\x14\x00\x08\x08\..........
\r\n--uuid:6da6da4c-b94a-4ef0-9c56-5f918a000a29--
```
binary code begin with \r\n\r\n and ending \r\n

i test on http.route method  with following code:

```
start_idx = line.index('\r\n\r\n', idx) + len('\r\n\r\n')
                fin_idx = line.rindex('\r\n--', start_idx)
                file_body = line[start_idx: fin_idx]
```
saved without any problem.
i aded full request to attachment

[GiB_request.zip](https://github.com/arskom/spyne/files/2888664/GiB_request.zip)
thank you burak

**Comment by bumblebeey** [comment]
its my final stage, if you can fix or help me i will be really happy.

**Comment by plq** [comment]
hey,

your example data works for me. data saved as zip file successfully.

**Comment by bumblebeey** [comment]
if we are test same way, what can be problem ? i try python 3.5-3.6-.37 all versions.
how can u test ?

**Comment by bumblebeey** [comment]
all codes same with your code.  i dont understant why getting problem with my code. i convert following dbugged binary code. expect spyne same error happen

**Comment by bumblebeey** [comment]
also can u test saced data to extract ?
