### ISSUE TITLE
Encoding issue on multipart related binary content

### ISSUE THREAD

**Issue by bumblebeey** [arskom/spyne#603]
Hi, i discover an error on multipart xml content
if attached binary zip  xml file include extra base64 content getting zip file damaged

like photo this xml file from damaged zip ( can extract only part of  begin and until image)

![error_file](https://user-images.githubusercontent.com/36727598/53240024-98f65280-36ae-11e9-9566-d7596da1346c.jpg)

if zip xml e doenst include similar content saving without any problem.

i have tested similar request with @http.route 
and when i try decode with (ascii, or UTF-8 ) show me cant decode part error
when i try decode with (iso-8859-1 or latin-1) decoded successfuly and attached binary object saved without error.

**Comment by plq** [comment]
This doesn't give me much to work with. Please provide a self-contained example, very much like https://github.com/plq/spyne/tree/master/examples/xml/soap12-mtom complete with server code and payload to simulate and I can have a look.

**Comment by bumblebeey** [comment]
i think response data is decoded data. how can i catch first response  for your test ?

**Comment by bumblebeey** [comment]
This file contain orginal request catched with request.httprequest.data
[for_Test.txt](https://github.com/arskom/spyne/files/2894929/for_Test.txt)

this file saved from request  data after decode with iso-8859-1 decode
[FD9FB8D0-A5C6-4EAB-B229-77C6DDE39C5A.zip](https://github.com/arskom/spyne/files/2894935/FD9FB8D0-A5C6-4EAB-B229-77C6DDE39C5A.zip)

i dont know how to convert binary in to curl . maybe following files can help you

**Comment by bumblebeey** [comment]
an note in the txt :
GIB file decoded with iso-8859-1 and base64:
only file part of saved file , file_body is only decoded(iso-8859-1) part of binary

with open(file_name, "wb") as code:
                    code.write(file_body.encode("iso-8859-1"))

**Comment by plq** [comment]
The attached files are fine. I don't see any problem.  [FD9FB8D0-A5C6-4EAB-B229-77C6DDE39C5A.zip](https://github.com/arskom/spyne/files/2894935/FD9FB8D0-A5C6-4EAB-B229-77C6DDE39C5A.zip) file decompresses successfully

**Comment by plq** [comment]
```
$ unzip -t FD9FB8D0-A5C6-4EAB-B229-77C6DDE39C5A.zip 
Archive:  FD9FB8D0-A5C6-4EAB-B229-77C6DDE39C5A.zip
    testing: FD9FB8D0-A5C6-4EAB-B229-77C6DDE39C5A.xml   OK
No errors detected in compressed data of FD9FB8D0-A5C6-4EAB-B229-77C6DDE39C5A.zip.

```

**Comment by bumblebeey** [comment]
Yes i save file with http route method. File getting healty, also txt file contain raw data. 
I attached file and body responses coz i cant sent with curl.

**Comment by bumblebeey** [comment]
I cant sent this file or requested data with curl, i attached responses , i dont know how, if u can send you will see zip will gone corrupt

**Comment by bumblebeey** [comment]
Also check file contained xml after send spyne, you will see turkish chars not correct eg: İ was show î etc

**Comment by plq** [comment]
> I cant sent this file or requested data with curl, i attached responses , i dont know how

Now is a good time to learn then!.

Reopen when you have something to show me.

**Comment by bumblebeey** [comment]
I send u healty file . You cant send it? Also i sent u healty base64 file data. Cant u sent it? 
I dont know how to pass binary with curl anyway thanks

**Comment by bumblebeey** [comment]
Also i fix my problem with manual decoding, problem is no more my problem, its spyne’s problem after then, as you wish fix or not. Have nice works, spyne is great job
