### ISSUE TITLE
Spyne SOAP server WSDL file cannot show https

### ISSUE THREAD

**Issue by waqashamid** [arskom/spyne#604]
My Spyne server WSDL shows 
`<soap:address location="http://some-domain.com>`

I want it to show `https` instead of `http`.

Basically, `<soap:address location="https://some-domain.com>`

Notice the difference lies in `http` and `https`.

How do I tell my Spyne server to address this?

Have gone through the docs multiple times but could not figure it out.

Thanks!

**Comment by plq** [comment]
Thanks for reaching out but this is the issue tracker. It's not for questions.

**Comment by waqashamid** [comment]
Thank you for reverting!

Well @plq it's almost impossible to get answers elsewhere.

I've asked the same question here: https://stackoverflow.com/questions/54920093/spyne-soap-server-wsdl-file-cannot-show-https

Can you please help me out? I'm really stuck here.

**Comment by RobertoMaurizzi** [comment]
@waqashamid as clearly stated in the README, "The official spyne discussion forum is at: people at spyne dot io. Subscribe either via http://lists.spyne.io/listinfo/people or by sending an empty message to: people-subscribe at spyne dot io."
