### ISSUE TITLE
How do I create a complex model with attriute, not element?Attribute

### ISSUE THREAD

**Issue by mXiaobingge** [arskom/spyne#607]
the wsdl i want to implent  is like this: 
<--complexType name="request-cac">
<--sequence>
<--element name="ip" type="xsd:string" minOccurs="1" maxOccurs="1" nillable="true"/>
<--element name="curtime" type="xsd:date" minOccurs="1" maxOccurs="1" nillable="true"/>
<--element name="operationtemperature" type="xsd:decimal" minOccurs="1" maxOccurs="1" nillable="true"/>
<--/sequence>
<--attribute name="id" type="xsd:string" use="required"/>
<--/complexType>
that is, with element and with attribute,  I have tried several methods, but i can't make it . I want to know if this lib can do this, and how to do this.

thanks.

my email is :    wangxh0827@126.com

**Comment by mXiaobingge** [comment]
<complexType name="request-cac">
<sequence>
<element name="ip" type="xsd:string" minOccurs="1" maxOccurs="1" nillable="true"/>
<element name="curtime" type="xsd:date" minOccurs="1" maxOccurs="1" nillable="true"/>
<element name="operationtemperature" type="xsd:decimal" minOccurs="1" maxOccurs="1" nillable="true"/>
</sequence>
<attribute name="id" type="xsd:string" use="required"/>
</complexType>

**Comment by mXiaobingge** [comment]
1.

**Comment by plq** [comment]
no questions in the issue tracker.

**Comment by mXiaobingge** [comment]
Dear sir:

I am very sorry to bother you.

I try to explan my question again.

I want to use spyne lib to realize my webservice. This figure shows one schema named uploadHeartbeatInfo.





Here is an example.



We can see that the sensor has one attribute named ‘id’, and has two element named ‘status’ and ‘operationtemperture’.

Element and attribute are defined differently in wsdl. Like this:

<complexType name="sensor">

<sequence>

<element name="status" type="xsd:string" minOccurs="1" />

<element name =" operationtemperature " type="xsd:string" />

</sequence>

<attribute name="id" type="xsd:string" use="required"/>

</complexType>

 

Now, I use spyne lib to define my model. But I cannot find the method to define the model’s attribute. i have tried like this.

Obviousely,  the id and status and operatontemperature are all element.
So, i want to ask how to define the attribute. 


--

    祝生活愉快，工作顺利！
    ——————————
    汪晓华 清华四川能源互联网研究院
    邮箱：wangxh0827@126.com
    手机：13550265109

At 2019-03-20 12:39:39, "Burak Arslan" <notifications@github.com> wrote:


Closed #607.

**Comment by plq** [comment]
> I try to explan my question again. 

Again, no questions in the issue tracker. Use the mailing list or stackoverflow.
