### ISSUE TITLE
Suggest to use wsdl-viewer for generated wsdl

### ISSUE THREAD

**Issue by vbashkirtsev** [arskom/spyne#616]
I would highly recommend to add wsdl-viewer.xsl from https://github.com/tomi-vanek/wsdl-viewer to spyne.  All is needed is to add header:

&lt;?xml-stylesheet type="text/xsl" href="wsdl-viewer.xsl"?>

to generated WSDL and supply wsdl-viewer.xsl along with WSDL say on url ending with ?wsdl-viewer.xsl . This way when WSDL is opened manually in a good browser it will be much more pleasing for a human to read. SOAP clients of course are not concerned with XSLT stylesheets and just continue to work as usual.

**Comment by plq** [comment]
Good idea, I will have a look at it. Thanks!
