### ISSUE TITLE
2.13 release

### ISSUE THREAD

**Issue by bgermann** [arskom/spyne#617]
Hi, when do you plan to release a 2.13 version? It would be great to have the Python 3 support in a stable release. You probably know that Python 2 reaches its end of life January 2020.

**Comment by plq** [comment]
Hello,

First, thanks for your taking time to reach out.

Spyne development continues and I'm doing regular releases on pypi. I know that they are tagged alpha and I haven't done a stable release in years, but I'm doing the best I can.

In the mean time, in case anyone stumbles upon this issue and wants to help, here are the tests that do not pass on Python 3:

https://jenkins.arskom.com.tr/job/spyne/job/origin-devel/PYFLAV=cpy-3.7/lastCompletedBuild/testReport/

If you (or anybody else who is interested) want to help, you are more than welcome to do so. However, please understand that I just can't tag a release with so many red tests stable and be done with it.

Best regards,
