### ISSUE TITLE
Undocumented MIT license from pyparsing

### ISSUE THREAD

**Issue by bgermann** [arskom/spyne#630]
Commit 216370b ("stole regex inverter from pyparsing") introduced the file spyne/util/invregexp.py without adding its license information. The [original version's](https://github.com/pyparsing/pyparsing/blob/a7f9dda0668bfce4fba51df1bf2976b4a93a8bd5/src/examples/invRegex.py) LICENSE file is MIT (Expat).

**Comment by plq** [comment]
Hey, thanks for the nitpick :)

Do you think it's OK if this went to the file's header?

**Comment by bgermann** [comment]
Sure.

**Comment by plq** [comment]
Done in e0cf4ed9b1f3f3137d56672d08cac6cad25b96ae. Reopen if not happy
