### ISSUE TITLE
New official release?

### ISSUE THREAD

**Issue by brot** [arskom/spyne#632]
When are you planning to release the next official version of spyne?

The latest official release was 2.12.6 from 2019-01-18.
In the meantime you made important changes to support Python 3.7 und 3.8 in the 2.13.x alpha releases. 
Also the latest changes are not even available as a alpha version on pypi

So it would be great to see a new official release which includes Python 3.7 and 3.8 support.

**Comment by plq** [comment]
Hey, thanks for the note.

The thing is, I can't make a non-alpha release with known test failures. However, I can make another pypi release that includes new stuff. I can handle that tomorrow.

**Comment by brot** [comment]
What's the problem with the test failures? What needs to be fixed? Is there something you need help with?

**Comment by plq** [comment]
https://jenkins.arskom.com.tr/job/spyne/job/origin-devel/lastCompletedBuild/testReport/

**Comment by brot** [comment]
@plq 
There are now two pull request which should help with the failing tests
https://github.com/arskom/spyne/pull/628
https://github.com/arskom/spyne/pull/633

Does this make a new official version release now possible?

**Comment by plq** [comment]
the beta is now out. the stable will be out 1 month from now, assuming no bugs reported.

**Comment by bgermann** [comment]
Hey! one month has passed since the last beta. How about a stable release?

**Comment by brot** [comment]
@plq you wrote on 2020-01-09
> the beta is now out. the stable will be out 1 month from now, assuming no bugs reported.

Nearly three month has passed since your comment. What are your plans for the new release? It would be great to have a release out there with official Python3 support!

**Comment by brot** [comment]
Not sure why this issue is closed now, because the latest release is still 2.13.14-beta which we have to use to be able to run on Python 3.7.
So I new stable release would be highly appreciated. 

And also seeing a new release with the newest commits (e.g. 006bffef74113f85493f18c01a3e847f49962b92) would be great to get rid of the DeprecationWarning
