### ISSUE TITLE
ctx.descriptor.udp unavailable

### ISSUE THREAD

**Issue by azurit** [arskom/spyne#643]
In version 2.13.14-beta, ctx.descriptor.udp is unavailable:
`AttributeError: 'MethodDescriptor' object has no attribute 'udp'`

From spyne-2.13.2-alpha changelog:
`_udp argument to @rpc was deprecated in favour of _udd. UDP is too well known as user datagram protocol which could be confusing.`

I suppose that 'deprecated' means 'udp' will be available for some time along with 'udd', so this is probably a bug.

**Comment by plq** [comment]
> I suppose that 'deprecated' means 'udp' will be available for some time along with 'udd', so this is probably a bug.

Correct. I'll fix this shortly.

**Comment by azurit** [comment]
Thank you!

**Comment by plq** [comment]
this patch is merged to master. a release will be made shortly
