### ISSUE TITLE
how to use `throttle_classes` for spyne application with django

### ISSUE THREAD

**Issue by chiragkanhasoft** [arskom/spyne#652]
I want to use `throttle_classes` for my API which has spyne application, i found below link to implement it in url.py file, but it is not working for spyne DjangoView.

[Link for use classes in URL](https://stackoverflow.com/questions/60666418/remove-authentication-and-permission-for-specific-url-path
)

i have tried like this.

url(
        r"^vapi/",
        (permission_classes([IsAuthenticated])(vapi_view.vapp)).as_view(application=vapi_view.vapp),
    ),

**Comment by plq** [comment]
no questions in the issue tracker. use [discussions](https://github.com/arskom/spyne/discussions) please.
