### ISSUE TITLE
spyne.model.complex.XmlAttribute issue

### ISSUE THREAD

**Issue by minafarouk** [arskom/spyne#656]
I am trying to upgrade spyne from **2.10.9** to **2.13.16** but I got error: "`TypeError: __new__() got an unexpected keyword argument 'attribute_of`' " for

```
class AVPairList(ComplexModel):
    AVPair = String(max_occurs='unbounded')
    Name = XmlAttribute(String, attribute_of='AVPair')
```

**Comment by gopackgo90** [comment]
`attribute_of` was removed in 2.13.3-alpha, see https://github.com/arskom/spyne/commit/2a483f34b1a50ccb35e7370ff86cb599281b7cbb.
