### ISSUE TITLE
ComplexModels attempting to use in-line customization are silently dropped from inheriting objects

### ISSUE THREAD

**Issue by packplusplus** [arskom/spyne#657]
Bug or Documentation update? 

If you have a complex object, that inherits another complex object, and you try to use inline customization for that inherited object, the object is silently dropped from the inheriting object. 

Example: 
```
from spyne import Application, rpc, ServiceBase, String
from spyne.protocol.soap import Soap11
from spyne.server.wsgi import WsgiApplication
from spyne.model.complex import ComplexModel, Array

class Obj1(ComplexModel):
    D = String(min_occurs = 0, max_occurs = 1)

class Obj2(ComplexModel):
    # Obj1 gets siletly dropped from obj2 when instantiating obj2
    A = Obj1(min_occurs = 0, max_occurs = 1)

    # works as expected
    B = Obj1

    # works, and throws enforces nillability
    C= Obj1.customize(min_occurs = 1, max_occurs = 1, nillable = False)

class soapResponse(ComplexModel):
    results = Array(Obj2)

class App(ServiceBase):

    @rpc( _body_style='bare', _returns=soapResponse)
    def retrievePolicy(ctx):
        o1 = Obj1(D = "2021-01-01")
        print(o1)

        o2 = Obj2(
            A = o1,
            B = o1,
            C = o1
        )
        print(o2)

        rpd = soapResponse(results = [o2] )
        print(rpd)
        return rpd

if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    wsgi_app = WsgiApplication(Application([App],
        tns='http://atlas-fin.com/',
        in_protocol=Soap11(validator='soft'),
        out_protocol=Soap11()
    ))
    server = make_server('0.0.0.0', 80, wsgi_app)
    server.serve_forever()
```

Output from the server 
```
Obj1(D='2021-01-01')
Obj2(B=Obj1(D='2021-01-01'), C=Obj1(D='2021-01-01'))
soapResponse(results=[Obj2(B=Obj1(D='2021-01-01'), C=Obj1(D='2021-01-01'))])
```

Obviously A is a syntax error, the other two work correctly. From a beginning user perspective, change the type from a developer defined complexModel to a basic model like string and the code starts working, change back and it doesn't. 

After reading http://spyne.io/docs/2.10/manual/03_types.html 10 times, it became clear that none of the examples use `myType(min_occurs=1)`, so in some ways the documentation reflects reality. Further more, the docs do say `Calling simple types directly is a shortcut to their customize method:`, so I get it, there are clues there, and no where are the docs "wrong".

Some possible positive outcomes from my experience:
* This is actually a bug, and complexModels are supposed to have the same short cut as simple models, the bug gets resolved. I don't think I can help with this, but hopefully my sample code gets a dev a head start on the testing.
* This is actually a bug, errors should be thrown when you ask spyne to do something it can't and not silently drop data.
* There are reasons under the covers complexModels can't have the same short cut as simple models, and that it's impossible or too gross to throw an error if someone tries to use the shortcut, so this is a crappy, but unfixable behavior. Maybe an improvement to the documentation can help? I can open a PR with some suggested changes.
*  There is a way to wire this short cut up for complexModels, and the documentation could use a clear example of how to do this. If I had that sample code, I could open a PR with that code added and some suggested changes.

Thoughts?

**Comment by plq** [comment]
hey,

i may be stuck at home but it's still a nice friday evening, so just a quick response:

``SomeComplexModel(foo=bla, bar=bla, ...)`` *instantiates* said model. no way around that as that's how python classes work.
``Integer64(min_occurs=1)`` *customizes* said model. if you want to instantiate, use ``int()`` or ``Integer64.Value()`` if you want to be consistent.

```
class Obj2(ComplexModel):
    # Obj1 gets siletly dropped from obj2 when instantiating obj2
    A = Obj1(min_occurs = 0, max_occurs = 1)

```

the code here sets a class variable as A. ``ComplexModelMeta`` ignores it as it's a legitimate python instantiation. you need ``Obj1.customize()`` if you want to establish a has-a relationship between Obj2 and Obj1.

If this doesn't help that's probably because i only skimmed your question and i'll look at this more closely when it's work time, so bear with me

best,

**Comment by packplusplus** [comment]
I'm reading that as `There are reasons under the covers complexModels can't have the same short cut as simple models`, and I'm going to take a swing at a doc update to make this more clear to a new dev. Since this is an expected behavior, I'm going to close this issue, and reference it in the PR.
