### ISSUE TITLE
spyne.server.django.DjangoView.as_view small bug

### ISSUE THREAD

**Issue by marcperrinoptel** [arskom/spyne#667]
There seems to be a bug in `spyne.server.django.DjangoView.as_view`:
If you use `'server'` in the `initkwargs`, the call to `cls(server=server, **initkwargs)` will fail with `'keyword argument repeated'`.
`'server'` should be popped from the `initkwargs` instead of get.

**Comment by plq** [comment]
thanks for the heads-up. reopen if not happy
