### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by matclayton** [arskom/spyne#700]
**Describe the bug**
Spyne installs but causes import issues with Python 3.12 

**To Reproduce**
Install and use Spyne under Python 3.12

**Additional context**
Nothing really to add here, except the issue seems related to the vendored six module and specifically spyne.util.six.moves no longer being available. 

This looks like the cause of the bug after my initial check https://github.com/benjaminp/six/issues/376

**Comment by syphar** [comment]
@plq is it possible to create a release with this fix? 

What could we do to help with it? 

Thanks! ❤️

**Comment by plq** [comment]
I filed #705. Can't say more than "it's a high priority task in my backlog".

**Comment by fmg-adam-johnson** [comment]
@plq any updates on ETA of release?

**Comment by shivam-2pointers** [comment]
@plq A release for this would really be appreciated! Any idea when?

**Comment by zackfall** [comment]
So, we'll never get this update?
